from app.modules.infrastructure_sector.meteorologia.infrastructure.models.estacao_model import EstacaoMeteorologicaModel
from app.modules.infrastructure_sector.meteorologia.infrastructure.models.observacao_model import ObservacaoMeteorologicaModel
__all__ = ['EstacaoMeteorologicaModel', 'ObservacaoMeteorologicaModel']