#!/usr/bin/env python3
"""Gera estrutura enterprise do modulo estatistica de forma idempotente."""

from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

DIRS = [
    "api/endpoints",
    "api/schemas",
    "application/events",
    "application/handlers",
    "application/ports",
    "application/services",
    "domain/models",
    "domain/value_objects",
    "infrastructure/adapters",
    "infrastructure/models",
    "infrastructure/persistence",
    "infrastructure/repositories",
    "infrastructure/resilience",
    "data_sources",
    "events",
    "workers",
    "integrations",
    "tests",
    "resilience",
]

FILES = [
    "exceptions.py",
    "config.py",
    "api/deps.py",
    "api/router.py",
    "api/endpoints/dashboards.py",
    "api/endpoints/kpis.py",
    "api/endpoints/relatorios.py",
    "api/endpoints/metricas.py",
    "api/endpoints/timeseries.py",
    "api/endpoints/agregacoes.py",
    "api/endpoints/exportacoes.py",
    "api/endpoints/indicadores.py",
    "api/endpoints/analises.py",
    "api/endpoints/previsoes.py",
    "api/endpoints/comparativos.py",
    "api/endpoints/rankings.py",
    "api/endpoints/tendencias.py",
    "api/endpoints/alertas.py",
    "api/schemas/dashboard_schema.py",
    "api/schemas/kpi_schema.py",
    "api/schemas/relatorio_schema.py",
    "api/schemas/metrica_schema.py",
    "api/schemas/timeseries_schema.py",
    "api/schemas/agregacao_schema.py",
    "api/schemas/exportacao_schema.py",
    "api/schemas/indicador_schema.py",
    "api/schemas/analise_schema.py",
    "api/schemas/previsao_schema.py",
    "api/schemas/comparativo_schema.py",
    "api/schemas/ranking_schema.py",
    "api/schemas/tendencia_schema.py",
    "api/schemas/alerta_schema.py",
    "application/bus.py",
    "application/events/definitions.py",
    "application/events/metrica_events.py",
    "application/events/registry.py",
    "application/handlers/agregacao_handler.py",
    "application/handlers/notificacao_handler.py",
    "application/ports/dashboard_repository_port.py",
    "application/ports/kpi_repository_port.py",
    "application/ports/metrica_repository_port.py",
    "application/ports/timeseries_repository_port.py",
    "application/ports/relatorio_repository_port.py",
    "application/ports/indicador_repository_port.py",
    "application/ports/agregacao_repository_port.py",
    "application/ports/outbox_repository_port.py",
    "application/ports/agricultura_data_source_port.py",
    "application/ports/ambiente_data_source_port.py",
    "application/ports/assistencia_social_data_source_port.py",
    "application/ports/comercio_externo_data_source_port.py",
    "application/ports/educacao_data_source_port.py",
    "application/ports/emprego_data_source_port.py",
    "application/ports/energia_data_source_port.py",
    "application/ports/financas_data_source_port.py",
    "application/ports/saude_data_source_port.py",
    "application/ports/turismo_data_source_port.py",
    "application/ports/transportes_data_source_port.py",
    "application/ports/urbanismo_data_source_port.py",
    "application/services/dashboard_service.py",
    "application/services/kpi_service.py",
    "application/services/metrica_service.py",
    "application/services/timeseries_service.py",
    "application/services/relatorio_service.py",
    "application/services/indicador_service.py",
    "application/services/agregacao_service.py",
    "application/services/exportacao_service.py",
    "application/services/analise_service.py",
    "application/services/previsao_service.py",
    "application/services/comparativo_service.py",
    "application/services/ranking_service.py",
    "application/services/tendencia_service.py",
    "application/services/alerta_service.py",
    "domain/enums.py",
    "domain/exceptions.py",
    "domain/value_objects/metrica_id.py",
    "domain/value_objects/kpi_id.py",
    "domain/value_objects/periodo.py",
    "domain/value_objects/valor_metrica.py",
    "domain/models/dashboard.py",
    "domain/models/kpi.py",
    "domain/models/metrica.py",
    "domain/models/timeseries.py",
    "domain/models/relatorio.py",
    "domain/models/indicador.py",
    "domain/models/agregacao.py",
    "domain/models/exportacao.py",
    "domain/models/analise.py",
    "domain/models/previsao.py",
    "domain/models/comparativo.py",
    "domain/models/ranking.py",
    "domain/models/tendencia.py",
    "domain/models/alerta.py",
    "infrastructure/adapters/agricultura_data_source_adapter.py",
    "infrastructure/adapters/ambiente_data_source_adapter.py",
    "infrastructure/adapters/assistencia_social_data_source_adapter.py",
    "infrastructure/adapters/comercio_externo_data_source_adapter.py",
    "infrastructure/adapters/educacao_data_source_adapter.py",
    "infrastructure/adapters/emprego_data_source_adapter.py",
    "infrastructure/adapters/energia_data_source_adapter.py",
    "infrastructure/adapters/financas_data_source_adapter.py",
    "infrastructure/adapters/saude_data_source_adapter.py",
    "infrastructure/adapters/turismo_data_source_adapter.py",
    "infrastructure/adapters/transportes_data_source_adapter.py",
    "infrastructure/adapters/urbanismo_data_source_adapter.py",
    "infrastructure/models/dashboard_model.py",
    "infrastructure/models/kpi_model.py",
    "infrastructure/models/metrica_model.py",
    "infrastructure/models/timeseries_model.py",
    "infrastructure/models/relatorio_model.py",
    "infrastructure/models/indicador_model.py",
    "infrastructure/models/agregacao_model.py",
    "infrastructure/models/exportacao_model.py",
    "infrastructure/models/analise_model.py",
    "infrastructure/models/previsao_model.py",
    "infrastructure/models/comparativo_model.py",
    "infrastructure/models/ranking_model.py",
    "infrastructure/models/tendencia_model.py",
    "infrastructure/models/alerta_model.py",
    "infrastructure/models/outbox_event_model.py",
    "infrastructure/persistence/outbox.py",
    "infrastructure/repositories/sqlalchemy_dashboard_repository.py",
    "infrastructure/repositories/sqlalchemy_kpi_repository.py",
    "infrastructure/repositories/sqlalchemy_metrica_repository.py",
    "infrastructure/repositories/sqlalchemy_timeseries_repository.py",
    "infrastructure/repositories/sqlalchemy_relatorio_repository.py",
    "infrastructure/repositories/sqlalchemy_indicador_repository.py",
    "infrastructure/repositories/sqlalchemy_agregacao_repository.py",
    "infrastructure/repositories/sqlalchemy_exportacao_repository.py",
    "infrastructure/repositories/sqlalchemy_analise_repository.py",
    "infrastructure/repositories/sqlalchemy_previsao_repository.py",
    "infrastructure/repositories/sqlalchemy_comparativo_repository.py",
    "infrastructure/repositories/sqlalchemy_ranking_repository.py",
    "infrastructure/repositories/sqlalchemy_tendencia_repository.py",
    "infrastructure/repositories/sqlalchemy_alerta_repository.py",
    "infrastructure/repositories/sqlalchemy_outbox_repository.py",
    "infrastructure/resilience/circuit_breaker.py",
    "infrastructure/resilience/retry.py",
    "data_sources/base_data_source.py",
    "data_sources/agricultura_source.py",
    "data_sources/ambiente_source.py",
    "data_sources/assistencia_social_source.py",
    "data_sources/comercio_externo_source.py",
    "data_sources/educacao_source.py",
    "data_sources/emprego_source.py",
    "data_sources/energia_source.py",
    "data_sources/financas_source.py",
    "data_sources/saude_source.py",
    "data_sources/turismo_source.py",
    "data_sources/transportes_source.py",
    "data_sources/urbanismo_source.py",
    "events/bus.py",
    "events/definitions.py",
    "workers/agregacao_worker.py",
    "workers/kpi_calculation_worker.py",
    "workers/timeseries_worker.py",
    "workers/relatorio_worker.py",
    "workers/outbox_worker.py",
    "integrations/bi_connector.py",
    "tests/conftest.py",
    "tests/_fakes.py",
    "tests/test_dashboards.py",
    "tests/test_kpis.py",
    "tests/test_metricas.py",
    "tests/test_timeseries.py",
    "tests/test_relatorios.py",
    "tests/test_indicadores.py",
    "tests/test_agregacoes.py",
    "tests/test_exportacoes.py",
    "tests/test_analises.py",
    "tests/test_previsoes.py",
    "tests/test_comparativos.py",
    "tests/test_rankings.py",
    "tests/test_tendencias.py",
    "tests/test_alertas.py",
    "tests/test_data_sources.py",
    "tests/test_workers.py",
    "tests/test_integrations.py",
    "tests/test_orm_integration_real.py",
    "tests/test_e2e_fluxo_completo.py",
    "resilience/circuit_breaker.py",
    "resilience/retry.py",
]


if __name__ == "__main__":
    for dirname in DIRS:
        path = BASE_DIR / dirname
        path.mkdir(parents=True, exist_ok=True)

    # create __init__.py in every directory under module
    for path in [BASE_DIR, *BASE_DIR.rglob("*")]:
        if path.is_dir():
            init_file = path / "__init__.py"
            if not init_file.exists():
                init_file.write_text("", encoding="utf-8")

    for rel_path in FILES:
        file_path = BASE_DIR / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        if not file_path.exists():
            file_path.write_text("", encoding="utf-8")

    print(f"Estrutura gerada em: {BASE_DIR}")
    print(f"Diretorios garantidos: {len(DIRS)}")
    print(f"Arquivos garantidos: {len(FILES)}")
