from pathlib import Path

base = Path("apps/backend/app/modules/defesa_consumidor")
ideal_files = [
    "__init__.py",
    "exceptions.py",
    "api/__init__.py",
    "api/deps.py",
    "api/router.py",
    "api/endpoints/__init__.py",
    "api/endpoints/reclamacoes.py",
    "api/endpoints/mediacao.py",
    "api/endpoints/sancoes.py",
    "api/endpoints/consumidores.py",
    "api/endpoints/estabelecimentos.py",
    "api/endpoints/produtos.py",
    "api/endpoints/recalls.py",
    "api/endpoints/arbitragem.py",
    "api/schemas/__init__.py",
    "api/schemas/reclamacao_schema.py",
    "api/schemas/mediacao_schema.py",
    "api/schemas/sancao_schema.py",
    "api/schemas/consumidor_schema.py",
    "api/schemas/estabelecimento_schema.py",
    "api/schemas/produto_schema.py",
    "api/schemas/recall_schema.py",
    "api/schemas/arbitragem_schema.py",
    "application/__init__.py",
    "application/ports/__init__.py",
    "application/ports/reclamacao_repository_port.py",
    "application/ports/mediacao_repository_port.py",
    "application/ports/sancao_repository_port.py",
    "application/ports/consumidor_repository_port.py",
    "application/ports/estabelecimento_repository_port.py",
    "application/ports/produto_repository_port.py",
    "application/ports/citizen_service_port.py",
    "application/ports/comercio_servicos_service_port.py",
    "application/ports/justica_service_port.py",
    "application/ports/financas_service_port.py",
    "application/ports/request_service_port.py",
    "application/services/__init__.py",
    "application/services/reclamacao_service.py",
    "application/services/mediacao_service.py",
    "application/services/sancao_service.py",
    "application/services/consumidor_service.py",
    "application/services/estabelecimento_service.py",
    "application/services/produto_service.py",
    "application/services/recall_service.py",
    "application/services/arbitragem_service.py",
    "domain/__init__.py",
    "domain/enums.py",
    "domain/entities.py",
    "domain/value_objects/__init__.py",
    "domain/value_objects/numero_reclamacao.py",
    "domain/value_objects/cpf_cnpj.py",
    "domain/value_objects/protocolo.py",
    "domain/models/__init__.py",
    "domain/models/reclamacao.py",
    "domain/models/mediacao.py",
    "domain/models/sancao.py",
    "domain/models/consumidor.py",
    "domain/models/estabelecimento.py",
    "domain/models/produto.py",
    "domain/models/recall.py",
    "domain/models/arbitragem.py",
    "infrastructure/__init__.py",
    "infrastructure/adapters/__init__.py",
    "infrastructure/adapters/citizen_service_adapter.py",
    "infrastructure/adapters/comercio_servicos_adapter.py",
    "infrastructure/adapters/justica_service_adapter.py",
    "infrastructure/adapters/financas_service_adapter.py",
    "infrastructure/adapters/request_service_adapter.py",
    "infrastructure/models/__init__.py",
    "infrastructure/models/reclamacao_model.py",
    "infrastructure/models/mediacao_model.py",
    "infrastructure/models/sancao_model.py",
    "infrastructure/models/consumidor_model.py",
    "infrastructure/models/estabelecimento_model.py",
    "infrastructure/models/produto_model.py",
    "infrastructure/models/recall_model.py",
    "infrastructure/models/arbitragem_model.py",
    "infrastructure/repositories/__init__.py",
    "infrastructure/repositories/sqlalchemy_reclamacao_repository.py",
    "infrastructure/repositories/sqlalchemy_mediacao_repository.py",
    "infrastructure/repositories/sqlalchemy_sancao_repository.py",
    "infrastructure/repositories/sqlalchemy_consumidor_repository.py",
    "infrastructure/repositories/sqlalchemy_estabelecimento_repository.py",
    "infrastructure/repositories/sqlalchemy_produto_repository.py",
    "infrastructure/repositories/sqlalchemy_recall_repository.py",
    "infrastructure/repositories/sqlalchemy_arbitragem_repository.py",
    "events/__init__.py",
    "events/bus.py",
    "events/definitions.py",
    "events/handlers/__init__.py",
    "events/handlers/notificacao_handler.py",
    "workers/__init__.py",
    "workers/outbox_worker.py",
    "integrations/__init__.py",
    "integrations/fuc_client.py",
    "tests/__init__.py",
    "tests/conftest.py",
    "tests/test_reclamacoes.py",
    "tests/test_mediacoes.py",
    "tests/test_sancoes.py",
    "tests/test_consumidores.py",
    "tests/test_estabelecimentos.py",
    "tests/test_produtos.py",
    "tests/test_recalls.py",
    "tests/test_arbitragem.py",
    "tests/test_orm_integration_real.py",
    "resilience/__init__.py",
    "resilience/circuit_breaker.py",
    "resilience/retry.py",
]

for rel in ideal_files:
    path = base / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(f"'''placeholder {rel}'''\n")
        print("created", path)

print("done generation")
