#!/usr/bin/env python3
"""
SILA System Configuration Manager
Phase 2.2 - Environment Variable Configuration
"""

import logging
import os
import sys
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ConfigManager:
    """Configuration manager for SILA system environments"""

    def __init__(self, config_dir: str = "/opt/sila-system/config"):
        self.config_dir = Path(config_dir)
        self.environments = ["development", "staging", "production"]
        self.required_vars = {
            "database": [
                "DATABASE_URL",
                "ASYNC_DATABASE_URL",
                "POSTGRES_DB",
                "POSTGRES_HOST",
                "POSTGRES_PORT",
                "POSTGRES_USER",
                "POSTGRES_PASSWORD",
            ],
            "security": [
                "AUTH_SECRET_KEY",
                "ALGORITHM",
                "ACCESS_TOKEN_EXPIRE_MINUTES",
                "REFRESH_TOKEN_EXPIRE_DAYS",
            ],
            "api": ["BACKEND_CORS_ORIGINS", "ALLOWED_ORIGINS", "REACT_APP_API_URL"],
            "monitoring": ["PROMETHEUS_GATEWAY", "GRAFANA_PASSWORD"],
        }

    def load_environment(self, environment: str) -> dict[str, Any]:
        """Load configuration for specified environment"""
        if environment not in self.environments:
            raise ValueError(
                f"Invalid environment: {environment}. Must be one of {self.environments}"
            )

        env_file = self.config_dir / f".env.{environment}"

        if not env_file.exists():
            logger.warning(f"Environment file not found: {env_file}")
            return {}

        load_dotenv(env_file, override=True)

        config = {}
        for key in os.environ:
            config[key] = os.environ[key]

        logger.info(f"Loaded configuration for {environment} environment")
        return config

    def validate_configuration(self, environment: str) -> dict[str, list]:
        """Validate that all required variables are present"""
        config = self.load_environment(environment)
        missing_vars = {}

        for category, variables in self.required_vars.items():
            missing = []
            for var in variables:
                if var not in config or not config[var]:
                    missing.append(var)
            if missing:
                missing_vars[category] = missing

        if missing_vars:
            logger.warning(f"Missing configuration variables in {environment}: {missing_vars}")
        else:
            logger.info(f"All required configuration variables present in {environment}")

        return missing_vars

    def get_variable(self, key: str, environment: str, default: Any = None) -> Any:
        """Get specific configuration variable"""
        config = self.load_environment(environment)
        return config.get(key, default)

    def set_variable(self, key: str, value: Any, environment: str) -> None:
        """Set configuration variable (for runtime adjustments)"""
        os.environ[key] = str(value)
        logger.info(f"Set environment variable: {key} for {environment}")

    def generate_template(self, environment: str) -> str:
        """Generate configuration template for environment"""
        template = f"""# SILA System Configuration - {environment.upper()}
# Generated by ConfigManager - Phase 2.2

# ========================
# DATABASE CONFIGURATION
# ========================
DATABASE_URL=os.getenv("DATABASE_URL")sila_{environment}
ASYNC_DATABASE_URL=postgresql+asyncpg://username:password@localhost:5432/sila_{environment}
POSTGRES_DB=sila_{environment}
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=username
POSTGRES_PASSWORD=password

# ========================
# SECURITY CONFIGURATION
# ========================
AUTH_SECRET_KEY=your-secret-key-here
ALGORITHM=HS256
# 90 dias em minutos (90 * 24 * 60 = 129600)
ACCESS_TOKEN_EXPIRE_MINUTES=129600
# Refresh token também ajustado para 90 dias
REFRESH_TOKEN_EXPIRE_DAYS=90

# ========================
# API CONFIGURATION
# ========================
BACKEND_CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
ALLOWED_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
REACT_APP_API_URL=http://localhost:8000

# ========================
# APPLICATION CONFIGURATION
# ========================
PROJECT_NAME=SILA-System
ENVIRONMENT={environment}
DEBUG={"true" if environment == "development" else "false"}
LOG_LEVEL=INFO

# ========================
# MONITORING CONFIGURATION
# ========================
PROMETHEUS_GATEWAY=http://localhost:9090
GRAFANA_PASSWORD=your-grafana-password

# ========================
# ADDITIONAL CONFIGURATION
# ========================
# Add any additional environment-specific variables below
"""
        return template

    def list_environments(self) -> list:
        """List available environments"""
        return self.environments

    def get_environment_status(self) -> dict[str, bool]:
        """Check which environment files exist"""
        status = {}
        for env in self.environments:
            env_file = self.config_dir / f".env.{env}"
            status[env] = env_file.exists()
        return status


def main():
    """CLI interface for configuration management"""
    if len(sys.argv) < 2:
        print("Usage: python config_manager.py <command> [args]")
        print("Commands: load, validate, template, status")
        sys.exit(1)

    manager = ConfigManager()
    command = sys.argv[1]

    if command == "load":
        if len(sys.argv) < 3:
            print("Usage: python config_manager.py load <environment>")
            sys.exit(1)
        env = sys.argv[2]
        config = manager.load_environment(env)
        print(f"Loaded {len(config)} variables for {env}")

    elif command == "validate":
        if len(sys.argv) < 3:
            print("Usage: python config_manager.py validate <environment>")
            sys.exit(1)
        env = sys.argv[2]
        missing = manager.validate_configuration(env)
        if missing:
            print(f"Missing variables in {env}: {missing}")
        else:
            print(f"All required variables present in {env}")

    elif command == "template":
        if len(sys.argv) < 3:
            print("Usage: python config_manager.py template <environment>")
            sys.exit(1)
        env = sys.argv[2]
        template = manager.generate_template(env)
        print(template)

    elif command == "status":
        status = manager.get_environment_status()
        for env, exists in status.items():
            print(f"{env}: {'✅' if exists else '❌'}")

    else:
        print(f"Unknown command: {command}")


if __name__ == "__main__":
    main()
