from app.modules.educacao.application.ports import (
    BoletimRepositoryPort,
    CertificadoRepositoryPort,
    ConcursoRepositoryPort,
    EmpregoRepositoryPort,
    EscolaRepositoryPort,
    FormacaoRepositoryPort,
    InscricaoRepositoryPort,
    MatriculaRepositoryPort,
    PropinaRepositoryPort,
    TransferenciaRepositoryPort,
    TurmaRepositoryPort,
    UniversidadeRepositoryPort,
    WorkflowRepositoryPort,
)

__all__ = [
    "BoletimRepositoryPort",
    "CertificadoRepositoryPort",
    "ConcursoRepositoryPort",
    "EmpregoRepositoryPort",
    "EscolaRepositoryPort",
    "FormacaoRepositoryPort",
    "InscricaoRepositoryPort",
    "MatriculaRepositoryPort",
    "PropinaRepositoryPort",
    "TransferenciaRepositoryPort",
    "TurmaRepositoryPort",
    "UniversidadeRepositoryPort",
    "WorkflowRepositoryPort",
]
