services:
  db:
    image: postgres:16-alpine
    container_name: sila-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sila}
      POSTGRES_USER: ${POSTGRES_USER:-sila_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Trumanmarcelo_1983}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sila_user} -d ${POSTGRES_DB:-sila}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - sila-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      args:
        REQUIREMENTS_FILE: requirements/dev.txt
    container_name: sila-backend
    restart: unless-stopped
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ASYNC_DATABASE_URL=${ASYNC_DATABASE_URL}
      - RUN_MIGRATIONS=true
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./apps/backend:/app
      - uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: /app/entrypoint.sh
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - sila-network

  redis:
    image: redis:7-alpine
    container_name: sila-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sila-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: sila-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api/v1
    networks:
      - sila-network
    # Expondo a porta 80 para o Gateway Nginx poder consumir
    expose:
      - "80"

  gateway:
    image: nginx:1.25-alpine
    container_name: sila-gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - sila-network

volumes:
  postgres_data:
  uploads:


networks:
  sila-network:
    driver: bridge
