#!/usr/bin/env python3
"""
SILA System - Document Validation System
Validates documentation consistency, freshness, and integrity.
Integrates with CI/CD pipeline to ensure documentation quality.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple
from dataclasses import dataclass


@dataclass
class ValidationIssue:
    """Data class for validation issues."""

    severity: str  # 'error', 'warning', 'info'
    document: str
    issue_type: str
    message: str
    suggestion: str = ""


class DocumentValidator:
    """Main class for document validation and quality checks."""

    def __init__(self, project_root: str = None):
        """Initialize the validator with project root path."""
        self.project_root = (
            Path(project_root) if project_root else Path(__file__).parent.parent
        )
        self.docs_dir = self.project_root / "docs"
        self.scripts_dir = self.project_root / "scripts"

        # Validation rules
        self.max_age_days = 90  # Documents older than this are flagged
        self.required_metadata = ["generated_by", "generated_on", "system_version"]

    def load_traceability_data(self) -> Dict:
        """Load the traceability report generated by map_docs.py."""
        json_file = self.docs_dir / "RASTREABILIDADE_DOCUMENTACAO.json"

        if not json_file.exists():
            print(
                "⚠️  Warning: Traceability data not found. Run 'python scripts/map_docs.py' first."
            )
            return {}

        try:
            with open(json_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError) as e:
            print(f"❌ Error loading traceability data: {e}")
            return {}

    def check_document_age(self, document_data: Dict) -> List[ValidationIssue]:
        """Check if documents are too old and need updating."""
        issues = []

        for doc in document_data.get("documents", []):
            status = doc.get("status", "unknown")
            generated_on = doc.get("generated_on")

            # Check for obsolete documents
            if status == "obsolete":
                issues.append(
                    ValidationIssue(
                        severity="warning",
                        document=doc["document_path"],
                        issue_type="obsolete_document",
                        message=f"Document is older than {self.max_age_days} days",
                        suggestion="Review and update the document or its generator script",
                    )
                )

            # Check for documents without generation date
            elif status in ["no_date", "unknown"] and doc.get("generated_by"):
                issues.append(
                    ValidationIssue(
                        severity="warning",
                        document=doc["document_path"],
                        issue_type="missing_generation_date",
                        message="Document has generator but no generation date",
                        suggestion="Add 'generated_on' metadata to document header",
                    )
                )

        return issues

    def check_metadata_completeness(self, document_data: Dict) -> List[ValidationIssue]:
        """Check if documents have complete metadata."""
        issues = []

        for doc in document_data.get("documents", []):
            if doc.get("generated_by"):  # Only check generated documents
                missing_fields = []

                for field in self.required_metadata:
                    if not doc.get(field):
                        missing_fields.append(field)

                if missing_fields:
                    issues.append(
                        ValidationIssue(
                            severity="warning",
                            document=doc["document_path"],
                            issue_type="incomplete_metadata",
                            message=f"Missing metadata fields: {', '.join(missing_fields)}",
                            suggestion="Add missing metadata fields to document header",
                        )
                    )

        return issues

    def check_generator_script_exists(
        self, document_data: Dict
    ) -> List[ValidationIssue]:
        """Check if generator scripts referenced in documents actually exist."""
        issues = []

        for doc in document_data.get("documents", []):
            generator = doc.get("generated_by")
            if generator:
                script_path = self.scripts_dir / generator
                if not script_path.exists():
                    issues.append(
                        ValidationIssue(
                            severity="error",
                            document=doc["document_path"],
                            issue_type="missing_generator_script",
                            message=f"Generator script '{generator}' not found",
                            suggestion="Update generator script name or create the missing script",
                        )
                    )

    def check_script_can_run_generator(
        self, document_data: Dict
    ) -> List[ValidationIssue]:
        """Check if generator scripts are executable and can run."""
        issues = []

        for doc in document_data.get("documents", []):
            generator = doc.get("generated_by")
            if generator and (self.scripts_dir / generator).exists():
                script_path = self.scripts_dir / generator

                # Check if script is executable
                if not os.access(script_path, os.X_OK):
                    issues.append(
                        ValidationIssue(
                            severity="warning",
                            document=doc["document_path"],
                            issue_type="non_executable_generator",
                            message=f"Generator script '{generator}' is not executable",
                            suggestion="Run: chmod +x scripts/{generator}",
                        )
                    )

                # Try to validate Python scripts have no syntax errors
                if generator.endswith(".py"):
                    try:
                        result = subprocess.run(
                            [sys.executable, "-m", "py_compile", str(script_path)],
                            capture_output=True,
                            text=True,
                            timeout=30,
                        )
                        if result.returncode != 0:
                            issues.append(
                                ValidationIssue(
                                    severity="error",
                                    document=doc["document_path"],
                                    issue_type="generator_syntax_error",
                                    message=f"Generator script '{generator}' has syntax errors",
                                    suggestion=f"Fix syntax errors: {result.stderr.strip()}",
                                )
                            )
                    except (subprocess.TimeoutExpired, FileNotFoundError):
                        pass  # Skip if py_compile fails for other reasons

        return issues

    def check_document_consistency(self, document_data: Dict) -> List[ValidationIssue]:
        """Check for inconsistencies in document data."""
        issues = []

        # Check for duplicate documents
        paths = [doc["document_path"] for doc in document_data.get("documents", [])]
        duplicates = set([x for x in paths if paths.count(x) > 1])

        for duplicate in duplicates:
            issues.append(
                ValidationIssue(
                    severity="error",
                    document=duplicate,
                    issue_type="duplicate_document",
                    message="Document appears multiple times in traceability data",
                    suggestion="Review and clean up duplicate entries",
                )
            )

        return issues

    def check_document_format(self) -> List[ValidationIssue]:
        """Check document format and encoding issues."""
        issues = []

        if not self.docs_dir.exists():
            return issues

        for doc_file in self.docs_dir.rglob("*"):
            if doc_file.is_file() and not doc_file.name.startswith("."):
                try:
                    # Check if file is readable
                    with open(doc_file, "r", encoding="utf-8"):
                        pass
                except UnicodeDecodeError:
                    issues.append(
                        ValidationIssue(
                            severity="error",
                            document=str(doc_file.relative_to(self.project_root)),
                            issue_type="encoding_error",
                            message="Document has encoding issues (not UTF-8)",
                            suggestion="Convert document to UTF-8 encoding",
                        )
                    )
                except IOError as e:
                    issues.append(
                        ValidationIssue(
                            severity="error",
                            document=str(doc_file.relative_to(self.project_root)),
                            issue_type="file_read_error",
                            message=f"Cannot read document file: {e}",
                            suggestion="Check file permissions and integrity",
                        )
                    )

        return issues

    def run_all_validations(self) -> List[ValidationIssue]:
        """Run all validation checks and return list of issues."""
        all_issues = []
        document_data = self.load_traceability_data()

        if not document_data:
            all_issues.append(
                ValidationIssue(
                    severity="error",
                    document="traceability_system",
                    issue_type="missing_traceability_data",
                    message="No traceability data found",
                    suggestion="Run 'python scripts/map_docs.py' to generate traceability data",
                )
            )
            return all_issues

        # Run all validation checks
        validation_methods = [
            self.check_document_age,
            self.check_metadata_completeness,
            self.check_generator_script_exists,
            self.check_script_can_run_generator,
            self.check_document_consistency,
            self.check_document_format,
        ]

        for method in validation_methods:
            try:
                issues = method(document_data)
                all_issues.extend(issues)
            except Exception as e:
                all_issues.append(
                    ValidationIssue(
                        severity="error",
                        document="validation_system",
                        issue_type="validation_error",
                        message=f"Error during validation '{method.__name__}': {e}",
                        suggestion="Check validation logic and fix errors",
                    )
                )

        return all_issues

    def generate_validation_report(self, issues: List[ValidationIssue]) -> str:
        """Generate a formatted validation report."""
        if not issues:
            return "✅ All validations passed! Documentation is healthy."

        # Group issues by severity
        errors = [i for i in issues if i.severity == "error"]
        warnings = [i for i in issues if i.severity == "warning"]
        infos = [i for i in issues if i.severity == "info"]

        report = []
        report.append("# 🚨 Document Validation Report\n")
        report.append(f"**Generated:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n")

        if errors:
            report.append(f"\n## ❌ Errors ({len(errors)})\n")
            for issue in errors:
                report.append(f"### {issue.document}")
                report.append(f"- **Issue:** {issue.issue_type}")
                report.append(f"- **Message:** {issue.message}")
                if issue.suggestion:
                    report.append(f"- **Suggestion:** {issue.suggestion}")
                report.append("")

        if warnings:
            report.append(f"\n## ⚠️  Warnings ({len(warnings)})\n")
            for issue in warnings:
                report.append(f"### {issue.document}")
                report.append(f"- **Issue:** {issue.issue_type}")
                report.append(f"- **Message:** {issue.message}")
                if issue.suggestion:
                    report.append(f"- **Suggestion:** {issue.suggestion}")
                report.append("")

        if infos:
            report.append(f"\n## ℹ️  Information ({len(infos)})\n")
            for issue in infos:
                report.append(f"### {issue.document}")
                report.append(f"- **Issue:** {issue.issue_type}")
                report.append(f"- **Message:** {issue.message}")
                if issue.suggestion:
                    report.append(f"- **Suggestion:** {issue.suggestion}")
                report.append("")

        return "\n".join(report)

    def save_validation_report(
        self, issues: List[ValidationIssue], output_file: str = None
    ) -> str:
        """Save validation report to file."""
        if output_file is None:
            output_file = self.docs_dir / "VALIDATION_REPORT.md"

        report_content = self.generate_validation_report(issues)

        try:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(report_content)
            return str(output_file)
        except IOError as e:
            print(f"❌ Error saving validation report: {e}")
            return ""

    def should_fail_build(self, issues: List[ValidationIssue]) -> bool:
        """Determine if validation issues should fail the build."""
        return len([i for i in issues if i.severity == "error"]) > 0


def main():
    """Main function to run document validation."""
    print("🔍 Running document validation...")

    validator = DocumentValidator()
    issues = validator.run_all_validations()

    # Save report
    report_file = validator.save_validation_report(issues)
    if report_file:
        print(f"📋 Validation report saved to: {report_file}")

    # Output summary
    if issues:
        errors = len([i for i in issues if i.severity == "error"])
        warnings = len([i for i in issues if i.severity == "warning"])

        print(f"\n📊 Validation Results:")
        print(f"❌ Errors: {errors}")
        print(f"⚠️  Warnings: {warnings}")

        if errors > 0:
            print(f"\n🚨 Build should fail due to {errors} error(s)")
            sys.exit(1)
        else:
            print("✅ Validation passed with warnings only")
    else:
        print("✅ All validations passed!")

    print("\n" + "=" * 50)
    print(validator.generate_validation_report(issues))
    print("=" * 50)


if __name__ == "__main__":
    main()
