from app.modules.society.emprego.domain.models.candidato import Candidato
from app.modules.society.emprego.domain.models.oferta_emprego import DomainRecord as OfertaEmprego
from app.modules.society.emprego.domain.models.mediacao import DomainRecord as Mediacao
from app.modules.society.emprego.domain.models.inscricao_tecnica import DomainRecord as InscricaoTecnica
from app.modules.society.emprego.domain.models.formacao_profissional import DomainRecord as FormacaoProfissional
from app.modules.society.emprego.domain.models.alfabetizacao import DomainRecord as Alfabetizacao
from app.modules.society.emprego.domain.models.credenciamento import DomainRecord as Credenciamento
from app.modules.society.emprego.domain.models.formacao_certificada import DomainRecord as FormacaoCertificada
from app.modules.society.emprego.domain.models.reconversao import DomainRecord as Reconversao
from app.modules.society.emprego.domain.models.estagio_publico import DomainRecord as EstagioPublico
from app.modules.society.emprego.domain.models.declaracao_desemprego import DomainRecord as DeclaracaoDesemprego
from app.modules.society.emprego.domain.models.reclamacao_trabalhista import DomainRecord as ReclamacaoTrabalhista
from app.modules.society.emprego.domain.models.mediacao_conflito import DomainRecord as MediacaoConflito
from app.modules.society.emprego.domain.models.fiscalizacao_trabalho import DomainRecord as FiscalizacaoTrabalho
from app.modules.society.emprego.domain.models.registro_contrato import DomainRecord as RegistroContrato
from app.modules.society.emprego.domain.models.certificacao_profissional import DomainRecord as CertificacaoProfissional
from app.modules.society.emprego.domain.models.concurso_publico import DomainRecord as ConcursoPublico
from app.modules.society.emprego.domain.models.resultado_concurso import DomainRecord as ResultadoConcurso
from app.modules.society.emprego.domain.models.mobilidade_publica import DomainRecord as MobilidadePublica
from app.modules.society.emprego.domain.models.avaliacao_desempenho import DomainRecord as AvaliacaoDesempenho
from app.modules.society.emprego.domain.models.formacao_avancada import DomainRecord as FormacaoAvancada
from app.modules.society.emprego.domain.models.certificacao_competencias import DomainRecord as CertificacaoCompetencias
from app.modules.society.emprego.domain.models.capacitacao_qualidade import DomainRecord as CapacitacaoQualidade
from app.modules.society.emprego.domain.models.formacao_gestores import DomainRecord as FormacaoGestores