from .alfabetizacao_model import AlfabetizacaoModel
from .avaliacao_model import AvaliacaoModel
from .candidato_model import CandidatoModel
from .certificacao_model import CertificacaoModel
from .concurso_model import ConcursoModel
from .contrato_model import ContratoModel
from .credenciamento_model import CredenciamentoModel
from .declaracao_model import DeclaracaoModel
from .estagio_model import EstagioModel
from .fiscalizacao_model import FiscalizacaoModel
from .formacao_avancada_model import FormacaoAvancadaModel
from .formacao_model import FormacaoModel
from .inscricao_model import InscricaoModel
from .mediacao_model import MediacaoModel
from .mobilidade_model import MobilidadeModel
from .oferta_model import OfertaModel
from .reclamacao_model import ReclamacaoModel
from .resultado_model import ResultadoModel