from app.modules.society.assistencia_social.infrastructure.adapters.citizen_service_adapter import CitizenServiceAdapter
from app.modules.society.assistencia_social.infrastructure.adapters.educacao_service_adapter import EducacaoServiceAdapter
from app.modules.society.assistencia_social.infrastructure.adapters.emprego_service_adapter import EmpregoServiceAdapter
from app.modules.society.assistencia_social.infrastructure.adapters.juventude_service_adapter import JuventudeServiceAdapter
from app.modules.society.assistencia_social.infrastructure.adapters.request_service_adapter import RequestServiceAdapter
from app.modules.society.assistencia_social.infrastructure.adapters.saude_service_adapter import SaudeServiceAdapter
__all__ = ['CitizenServiceAdapter', 'EducacaoServiceAdapter', 'EmpregoServiceAdapter', 'JuventudeServiceAdapter', 'RequestServiceAdapter', 'SaudeServiceAdapter']