from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as AgregacaoCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as AgregacaoListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as AgregacaoResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as AgregacaoUpdate