from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as AnaliseCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as AnaliseListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as AnaliseResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as AnaliseUpdate