from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as ComparativoCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as ComparativoListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as ComparativoResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as ComparativoUpdate