from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as ExportacaoCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as ExportacaoListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as ExportacaoResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as ExportacaoUpdate