from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as IndicadorCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as IndicadorListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as IndicadorResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as IndicadorUpdate