from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as RankingCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as RankingListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as RankingResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as RankingUpdate