from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as RelatorioCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as RelatorioListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as RelatorioResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as RelatorioUpdate