from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityCreate as TendenciaCreate
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityListResponse as TendenciaListResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityResponse as TendenciaResponse
from app.modules.governance.statistics.api.schemas.generic_named_schema import NamedEntityUpdate as TendenciaUpdate