from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.ambiente_adapter import AmbienteAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.anacom_adapter import AnacomAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.anatel_adapter import AnatelAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.citizen_service_adapter import CitizenServiceAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.energia_adapter import EnergiaAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.financas_adapter import FinancasAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.geosampa_adapter import GeosampaAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.obras_publicas_adapter import ObrasPublicasAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.request_service_adapter import RequestServiceAdapter
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.adapters.urbanismo_adapter import UrbanismoAdapter
__all__ = ['AmbienteAdapter', 'AnacomAdapter', 'AnatelAdapter', 'CitizenServiceAdapter', 'EnergiaAdapter', 'FinancasAdapter', 'GeosampaAdapter', 'ObrasPublicasAdapter', 'RequestServiceAdapter', 'UrbanismoAdapter']