server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Compressão Gzip para performance em redes lentas
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml segmentation/octet-stream;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Cache agressivo para assets estáticos (Imagens/JS/CSS)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, imutável";
    }

    # Proteção básica
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
}
