from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.repositories.sqlalchemy_imovel_repository import SQLAlchemyImovelRepository
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.repositories.sqlalchemy_oneracao_repository import SQLAlchemyOneracaoRepository
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.repositories.sqlalchemy_proprietario_repository import SQLAlchemyProprietarioRepository
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.repositories.sqlalchemy_desapropriacao_repository import SQLAlchemyDesapropriacaoRepository
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.repositories.sqlalchemy_matricula_imovel_repository import SQLAlchemyMatriculaImovelRepository
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.repositories.sqlalchemy_georreferenciamento_repository import SQLAlchemyGeorreferenciamentoRepository
__all__ = ['SQLAlchemyImovelRepository', 'SQLAlchemyProprietarioRepository', 'SQLAlchemyOneracaoRepository', 'SQLAlchemyDesapropriacaoRepository', 'SQLAlchemyMatriculaImovelRepository', 'SQLAlchemyGeorreferenciamentoRepository']