from fastapi import APIRouter, Depends, Query, Request
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, text
from typing import Optional, List
from datetime import date
from core.db.session import get_async_db
from core.security import get_current_active_user
from modules.identity.models.user import User
from modules.documents.models.documents import Document
from modules.documents.schemas.documents import DocumentRead
from modules.audit.service import log_action

router = APIRouter(prefix="/search", tags=["search"])

@router.get("/deep", response_model=List[DocumentRead])
async def deep_ocr_search(
    q: str = Query(..., min_length=3, description="Palavra ou frase a buscar no conteúdo dos documentos"),
    status: Optional[str] = None,
    date_from: Optional[date] = None,
    date_to: Optional[date] = None,
    db: AsyncSession = Depends(get_async_db),
    current_user: User = Depends(get_current_active_user),
    request: Request = None,
):
    """Busca profunda no conteúdo OCR com realce de termos."""
    # Snippet de destaque (trecho relevante)
    # Using the requested mark class for Tailwind highlighting
    snippet = text("""
        ts_headline('portuguese', unaccent(ocr_text), plainto_tsquery('portuguese', unaccent(:q)), 
        'StartSel=<mark class="bg-yellow-300">, StopSel=</mark>, MaxFragments=3, FragmentDelimiter=...') 
    """).bindparams(q=q)

    # Base query
    query = select(Document, snippet.label("snippet")).where(Document.owner_id == current_user.id)

    if q:
        # Optimized Full-text search using the search_vector column with weights and GIN index
        query = query.where(text("search_vector @@ plainto_tsquery('portuguese', unaccent(:q))")).params(q=q)
        query = query.order_by(text("ts_rank(search_vector, plainto_tsquery('portuguese', unaccent(:q))) DESC")).params(q=q)

    if status:
        query = query.where(Document.status == status)

    if date_from:
        query = query.where(Document.created_at >= date_from)

    if date_to:
        query = query.where(Document.created_at <= date_to)

    if not q:
        query = query.order_by(Document.created_at.desc())

    result = await db.execute(query)
    rows = result.all()

    documents = []
    for doc, snippet_text in rows:
        doc_read = DocumentRead.model_validate(doc)
        # Fallback snippet if none generated by headline
        doc_read.highlight_snippet = snippet_text or f"Termo encontrado em {doc.original_filename}"
        documents.append(doc_read)

    await log_action(
        db=db,
        user_id=current_user.id,
        action="SEARCH_DOCUMENT_CONTENT",
        resource_id=None,
        details={"query": q, "results_count": len(documents)},
        request=request
    )

    return documents


@router.get("/documents", response_model=List[DocumentRead], deprecated=True)
async def search_documents_legacy(
    q: str = Query(..., description="Texto a buscar no conteúdo OCR ou nome do arquivo"),
    status: Optional[str] = None,
    date_from: Optional[date] = None,
    date_to: Optional[date] = None,
    db: AsyncSession = Depends(get_async_db),
    current_user: User = Depends(get_current_active_user),
):
    # Base query for user's documents
    query = select(Document).where(Document.owner_id == current_user.id)

    # Full-text search expression
    search_expr = "to_tsvector('portuguese', unaccent(COALESCE(ocr_text, '') || ' ' || COALESCE(original_filename, ''))) @@ plainto_tsquery('portuguese', unaccent(:q))"

    if q:
        query = query.where(text(search_expr)).params(q=q)

    if status:
        query = query.where(Document.status == status)

    if date_from:
        query = query.where(Document.created_at >= date_from)

    if date_to:
        query = query.where(Document.created_at <= date_to)

    # Ranking
    rank_expr = "ts_rank(to_tsvector('portuguese', unaccent(COALESCE(ocr_text, '') || ' ' || COALESCE(original_filename, ''))), plainto_tsquery('portuguese', unaccent(:q)))"
    
    if q:
        query = query.order_by(text(f"{rank_expr} DESC")).params(q=q)
    else:
        query = query.order_by(Document.created_at.desc())

    result = await db.execute(query)
    documents = result.scalars().all()

    return documents
