"""setup_unified_user_schema

Revision ID: 39a8297f4886
Revises: 
Create Date: 2025-12-27 13:10:57.180257

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = '39a8297f4886'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name: str = "") -> None:
    """Upgrade database schema and/or data, creating a new revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Base Tables (No dependencies)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)

    op.create_table('citizenship_citizens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizenship_citizens_email'), 'citizenship_citizens', ['email'], unique=True)
    op.create_index(op.f('ix_citizenship_citizens_id'), 'citizenship_citizens', ['id'], unique=True)
    op.create_index(op.f('ix_citizenship_citizens_name'), 'citizenship_citizens', ['name'], unique=False)

    op.create_table('citizenship_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('DOCUMENTOS', 'CERTIDOES', 'REGISTROS', 'AUTORIZACOES', 'LICENCAS', 'OUTROS', name='servicecategory'), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='prioritylevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizenship_services_code'), 'citizenship_services', ['code'], unique=True)

    op.create_table('payment_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_webhooks_active'), 'payment_webhooks', ['active'], unique=False)
    op.create_index(op.f('ix_payment_webhooks_id'), 'payment_webhooks', ['id'], unique=False)

    # 2. Users (Depends on locations)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bi_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bi_number'), 'users', ['bi_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)

    # 3. Tables depending on users
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)

    op.create_table('citizenship_atualizacao_b_i',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('morada', sa.String(length=500), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('motivo_atualizacao', sa.Text(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('dados_adicionais', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_email'), 'citizenship_atualizacao_b_i', ['email'], unique=False)
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_id'), 'citizenship_atualizacao_b_i', ['id'], unique=False)
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_nome_completo'), 'citizenship_atualizacao_b_i', ['nome_completo'], unique=False)
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_numero_documento'), 'citizenship_atualizacao_b_i', ['numero_documento'], unique=True)
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_status'), 'citizenship_atualizacao_b_i', ['status'], unique=False)
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_user_id'), 'citizenship_atualizacao_b_i', ['user_id'], unique=False)

    op.create_table('citizenship_service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('protocol_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'REJECTED', name='servicestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='prioritylevel'), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizenship_citizens.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['citizenship_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizenship_service_requests_citizen_id'), 'citizenship_service_requests', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_citizenship_service_requests_protocol_number'), 'citizenship_service_requests', ['protocol_number'], unique=True)

    op.create_table('document_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['document_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('identity_type', sa.String(length=50), nullable=False),
    sa.Column('identity_number', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_number')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.create_index(op.f('ix_identities_user_id'), 'identities', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT_SUCCESS', 'PAYMENT_FAILURE', 'DOCUMENT_SHARED', 'REFUND_PROCESSED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'CANCELLED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('method', sa.Enum('BNA', 'UNITEL_MONEY', 'M_PESA', 'MULTICAIXA', 'CREDIT_CARD', 'BANK_TRANSFER', 'CASH', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_owner_id'), 'payments', ['owner_id'], unique=False)

    # 4. Tables with Circular Dependencies
    # Create documents WITHOUT circular FK first
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_text_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folders.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)

    # Now add the circular FK to documents
    op.create_foreign_key('fk_documents_current_version', 'documents', 'document_versions', ['current_version_id'], ['id'])

    # 5. High dependency tables
    op.create_table('citizenship_service_request_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'IN_REVIEW', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'REJECTED', name='servicestatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'IN_REVIEW', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'REJECTED', name='servicestatus'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['citizenship_service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('citizenship_atualizacao_b_i_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bi_update_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bi_update_id'], ['citizenship_atualizacao_b_i.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_documents_bi_update_id'), 'citizenship_atualizacao_b_i_documents', ['bi_update_id'], unique=False)
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_documents_id'), 'citizenship_atualizacao_b_i_documents', ['id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT', 'REFUND', 'ADJUSTMENT', 'FEE', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED', 'CANCELLED', name='transactionstatus', native_enum=False), nullable=False),
    sa.Column('provider_reference', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED', 'CANCELLED', name='transactionstatus', native_enum=False), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)

    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['payment_webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_webhook_events_created_at'), 'payment_webhook_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_delivered'), 'payment_webhook_events', ['delivered'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_id'), 'payment_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_payment_id'), 'payment_webhook_events', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_webhook_events_webhook_id'), 'payment_webhook_events', ['webhook_id'], unique=False)

    op.create_table('payment_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_audit_logs_action'), 'payment_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_created_at'), 'payment_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_id'), 'payment_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_payment_audit_logs_payment_id'), 'payment_audit_logs', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade(engine_name: str = "") -> None:
    """Downgrade database schema and/or data back to the previous revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_webhook_events_webhook_id'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_payment_id'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_id'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_delivered'), table_name='payment_webhook_events')
    op.drop_index(op.f('ix_payment_webhook_events_created_at'), table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_documents_id'), table_name='citizenship_atualizacao_b_i_documents')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_documents_bi_update_id'), table_name='citizenship_atualizacao_b_i_documents')
    op.drop_table('citizenship_atualizacao_b_i_documents')
    op.drop_table('citizenship_service_request_history')
    op.drop_constraint('fk_documents_current_version', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_payments_owner_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_identities_user_id'), table_name='identities')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_table('document_folders')
    op.drop_index(op.f('ix_citizenship_service_requests_protocol_number'), table_name='citizenship_service_requests')
    op.drop_index(op.f('ix_citizenship_service_requests_citizen_id'), table_name='citizenship_service_requests')
    op.drop_table('citizenship_service_requests')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_user_id'), table_name='citizenship_atualizacao_b_i')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_status'), table_name='citizenship_atualizacao_b_i')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_numero_documento'), table_name='citizenship_atualizacao_b_i')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_nome_completo'), table_name='citizenship_atualizacao_b_i')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_id'), table_name='citizenship_atualizacao_b_i')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_email'), table_name='citizenship_atualizacao_b_i')
    op.drop_table('citizenship_atualizacao_b_i')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_bi_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_webhooks_id'), table_name='payment_webhooks')
    op.drop_index(op.f('ix_payment_webhooks_active'), table_name='payment_webhooks')
    op.drop_table('payment_webhooks')
    op.drop_index(op.f('ix_payment_audit_logs_payment_id'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_id'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_created_at'), table_name='payment_audit_logs')
    op.drop_index(op.f('ix_payment_audit_logs_action'), table_name='payment_audit_logs')
    op.drop_table('payment_audit_logs')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_citizenship_services_code'), table_name='citizenship_services')
    op.drop_table('citizenship_services')
    op.drop_index(op.f('ix_citizenship_citizens_name'), table_name='citizenship_citizens')
    op.drop_index(op.f('ix_citizenship_citizens_id'), table_name='citizenship_citizens')
    op.drop_index(op.f('ix_citizenship_citizens_email'), table_name='citizenship_citizens')
    op.drop_table('citizenship_citizens')
    # ### end Alembic commands ###
