"""add full_name to users

Revision ID: ec57433835a1
Revises: eb303b0fe34a
Create Date: 2025-12-28 10:58:11.485172

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ec57433835a1'
down_revision = 'eb303b0fe34a'
branch_labels = None
depends_on = None


def upgrade(engine_name: str = "") -> None:
    """Upgrade database schema and/or data, creating a new revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - adjusted ###
    op.create_table(
        'identities',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('identity_type', sa.String(length=50), nullable=False),
        sa.Column('identity_number', sa.String(length=100), nullable=False),
        sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('identity_number')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.create_index(op.f('ix_identities_user_id'), 'identities', ['user_id'], unique=False)

    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column(
        'users',
        sa.Column('administrative_level', sa.String(length=20), nullable=False, server_default='LOCAL')
    )

    op.drop_column('users', 'name')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade(engine_name: str = "") -> None:
    """Downgrade database schema and/or data back to the previous revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('users', sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'administrative_level')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_identities_user_id'), table_name='identities')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    # ### end Alembic commands ###