"""fix_user_and_bi_models

Revision ID: eb303b0fe34a
Revises: 39a8297f4886
Create Date: 2025-12-27 14:51:43.881852

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb303b0fe34a'
down_revision = '39a8297f4886'
branch_labels = None
depends_on = None


def upgrade(engine_name: str = "") -> None:
    """Upgrade database schema and/or data, creating a new revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_index(op.f('ix_identities_user_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_user_id'), table_name='citizenship_atualizacao_b_i')
    op.drop_column('citizenship_atualizacao_b_i', 'motivo_cancelamento')
    op.drop_column('citizenship_atualizacao_b_i', 'dados_adicionais')
    op.drop_index(op.f('ix_citizenship_atualizacao_b_i_documents_bi_update_id'), table_name='citizenship_atualizacao_b_i_documents')
    op.drop_column('citizenship_atualizacao_b_i_documents', 'verification_notes')
    op.drop_column('citizenship_atualizacao_b_i_documents', 'verification_date')
    op.drop_column('citizenship_atualizacao_b_i_documents', 'verified')
    # ### end Alembic commands ###


def downgrade(engine_name: str = "") -> None:
    """Downgrade database schema and/or data back to the previous revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizenship_atualizacao_b_i_documents', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('citizenship_atualizacao_b_i_documents', sa.Column('verification_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('citizenship_atualizacao_b_i_documents', sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_documents_bi_update_id'), 'citizenship_atualizacao_b_i_documents', ['bi_update_id'], unique=False)
    op.add_column('citizenship_atualizacao_b_i', sa.Column('dados_adicionais', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('citizenship_atualizacao_b_i', sa.Column('motivo_cancelamento', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_citizenship_atualizacao_b_i_user_id'), 'citizenship_atualizacao_b_i', ['user_id'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('identity_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('identities_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('identities_pkey')),
    sa.UniqueConstraint('identity_number', name=op.f('identities_identity_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_identities_user_id'), 'identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    # ### end Alembic commands ###


# Example of how to use the migration:
# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table(
#         'example_table',
#         sa.Column('id', sa.Integer(), nullable=False),
#         sa.Column('name', sa.String(length=255), nullable=False),
#         sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
#         sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
#         sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_example_table_name'), 'example_table', ['name'], unique=True)
#     # ### end Alembic commands ###

# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_example_table_name'), table_name='example_table')
#     op.drop_table('example_table')
#     # ### end Alembic commands ###
