"""add phone_number and address to users

Revision ID: 280ef11a337f
Revises: ec57433835a1
Create Date: 2025-12-28 12:14:49.024032

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = '280ef11a337f'
down_revision = 'ec57433835a1'
branch_labels = None
depends_on = None


def upgrade(engine_name: str = "") -> None:
    """Upgrade database schema and/or data, creating a new revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(engine_name: str = "") -> None:
    """Downgrade database schema and/or data back to the previous revision.

    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# Example of how to use the migration:
# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table(
#         'example_table',
#         sa.Column('id', sa.Integer(), nullable=False),
#         sa.Column('name', sa.String(length=255), nullable=False),
#         sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
#         sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
#         sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_example_table_name'), 'example_table', ['name'], unique=True)
#     # ### end Alembic commands ###

# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_example_table_name'), table_name='example_table')
#     op.drop_table('example_table')
#     # ### end Alembic commands ###
