from app.modules.infrastructure_sector.gestao_fundiaria.application.services.imovel_service import ImovelService
from app.modules.infrastructure_sector.gestao_fundiaria.application.services.oneracao_service import OneracaoService
from app.modules.infrastructure_sector.gestao_fundiaria.application.services.proprietario_service import ProprietarioService
from app.modules.infrastructure_sector.gestao_fundiaria.application.services.desapropriacao_service import DesapropriacaoService
from app.modules.infrastructure_sector.gestao_fundiaria.application.services.georreferenciamento_service import GeorreferenciamentoService
from app.modules.infrastructure_sector.gestao_fundiaria.application.services.matricula_imovel_service import MatriculaImovelService
__all__ = ['ImovelService', 'ProprietarioService', 'OneracaoService', 'DesapropriacaoService', 'MatriculaImovelService', 'GeorreferenciamentoService']