from app.modules.resources.pescas.domain.models.apreensao_embarcacao import ApreensaoEmbarcacao
from app.modules.resources.pescas.domain.models.area_pesca import AreaPesca
from app.modules.resources.pescas.domain.models.armador import Armador
from app.modules.resources.pescas.domain.models.arte_pesca import ArtePesca
from app.modules.resources.pescas.domain.models.auto_infracao_pesca import AutoInfracaoPesca
from app.modules.resources.pescas.domain.models.autorizacao_pesca import AutorizacaoPesca
from app.modules.resources.pescas.domain.models.beneficiamento import Beneficiamento
from app.modules.resources.pescas.domain.models.bitola_minima import BitolaMinima
from app.modules.resources.pescas.domain.models.cadeia_frio import CadeiaFrio
from app.modules.resources.pescas.domain.models.captura import Captura
from app.modules.resources.pescas.domain.models.certificado_origem_pesca import CertificadoOrigemPesca
from app.modules.resources.pescas.domain.models.comercializacao_pesca import ComercializacaoPesca
from app.modules.resources.pescas.domain.models.cooperativa_pesca import CooperativaPesca
from app.modules.resources.pescas.domain.models.defeso import Defeso
from app.modules.resources.pescas.domain.models.desembarque import Desembarque
from app.modules.resources.pescas.domain.models.embarcacao import Embarcacao
from app.modules.resources.pescas.domain.models.embargo_pesca import EmbargoPesca
from app.modules.resources.pescas.domain.models.empresa_pesca import EmpresaPesca
from app.modules.resources.pescas.domain.models.especie import Especie
from app.modules.resources.pescas.domain.models.estatistica_pesca import EstatisticaPesca
from app.modules.resources.pescas.domain.models.exportacao_pesca import ExportacaoPesca
from app.modules.resources.pescas.domain.models.fiscalizacao_pesca import FiscalizacaoPesca
from app.modules.resources.pescas.domain.models.frigorifico import Frigorifico
from app.modules.resources.pescas.domain.models.importacao_pesca import ImportacaoPesca
from app.modules.resources.pescas.domain.models.industria_pesca import IndustriaPesca
from app.modules.resources.pescas.domain.models.inspecao_sanitaria_pesca import InspecaoSanitariaPesca
from app.modules.resources.pescas.domain.models.laboratorio_qualidade import LaboratorioQualidade
from app.modules.resources.pescas.domain.models.licenca_pesca import LicencaPesca
from app.modules.resources.pescas.domain.models.monitoramento_satelite import MonitoramentoSatelite
from app.modules.resources.pescas.domain.models.multa_pesca import MultaPesca
from app.modules.resources.pescas.domain.models.observador_bordo import ObservadorBordo
from app.modules.resources.pescas.domain.models.permissao_pesca import PermissaoPesca
from app.modules.resources.pescas.domain.models.periodo_defeso import PeriodoDefeso
from app.modules.resources.pescas.domain.models.pescador import Pescador
from app.modules.resources.pescas.domain.models.pesquisa_pesqueira import PesquisaPesqueira
from app.modules.resources.pescas.domain.models.petrecho import Petrecho
from app.modules.resources.pescas.domain.models.producao_pesca import ProducaoPesca
from app.modules.resources.pescas.domain.models.quota import Quota
from app.modules.resources.pescas.domain.models.rastreabilidade_pesca import RastreabilidadePesca
from app.modules.resources.pescas.domain.models.recurso_pesqueiro import RecursoPesqueiro
from app.modules.resources.pescas.domain.models.safra import Safra
from app.modules.resources.pescas.domain.models.sistema_rastreamento import SistemaRastreamento
from app.modules.resources.pescas.domain.models.tamanho_minimo_captura import TamanhoMinimoCaptura
from app.modules.resources.pescas.domain.models.tipo_embarcacao import TipoEmbarcacao
from app.modules.resources.pescas.domain.models.vms import Vms
from app.modules.resources.pescas.domain.models.zona_pesca import ZonaPesca
__all__ = ['Pescador', 'Armador', 'EmpresaPesca', 'CooperativaPesca', 'Embarcacao', 'TipoEmbarcacao', 'ArtePesca', 'Petrecho', 'ZonaPesca', 'AreaPesca', 'RecursoPesqueiro', 'Especie', 'Safra', 'Quota', 'LicencaPesca', 'AutorizacaoPesca', 'PermissaoPesca', 'Defeso', 'PeriodoDefeso', 'Captura', 'Desembarque', 'ProducaoPesca', 'Beneficiamento', 'IndustriaPesca', 'Frigorifico', 'CadeiaFrio', 'ComercializacaoPesca', 'ExportacaoPesca', 'ImportacaoPesca', 'FiscalizacaoPesca', 'AutoInfracaoPesca', 'MultaPesca', 'EmbargoPesca', 'ApreensaoEmbarcacao', 'RastreabilidadePesca', 'CertificadoOrigemPesca', 'InspecaoSanitariaPesca', 'LaboratorioQualidade', 'MonitoramentoSatelite', 'SistemaRastreamento', 'Vms', 'ObservadorBordo', 'BitolaMinima', 'TamanhoMinimoCaptura', 'EstatisticaPesca', 'PesquisaPesqueira']