from apps.backend.app.modules.logistics.infrastructure.repositories.sqlalchemy_bilhetagem_repository import SQLAlchemyBilhetagemRepository
from apps.backend.app.modules.logistics.infrastructure.repositories.sqlalchemy_frota_repository import SQLAlchemyFrotaRepository
from apps.backend.app.modules.logistics.infrastructure.repositories.sqlalchemy_linha_repository import SQLAlchemyLinhaRepository
from apps.backend.app.modules.logistics.infrastructure.repositories.sqlalchemy_veiculo_repository import SQLAlchemyVeiculoRepository
from apps.backend.app.modules.logistics.infrastructure.repositories.sqlalchemy_viagem_repository import SQLAlchemyViagemRepository
__all__ = ['SQLAlchemyViagemRepository', 'SQLAlchemyFrotaRepository', 'SQLAlchemyLinhaRepository', 'SQLAlchemyVeiculoRepository', 'SQLAlchemyBilhetagemRepository']
