"""Base Aggregate Root - Phase 20: Domain-Driven Design"""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4


@dataclass
class DomainEvent:
    """Marker interface for domain events."""

    aggregate_id: UUID
    event_type: str
    version: int
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "aggregate_id": str(self.aggregate_id),
            "event_type": self.event_type,
            "version": self.version,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }


class BaseAggregate:
    """
    Base class for all aggregate roots.
    Aggregates enforce business rules and generate domain events.
    """

    def __init__(self, aggregate_id: UUID | None = None):
        self.id = aggregate_id or uuid4()
        self._version = 0
        self._uncommitted_events: list[DomainEvent] = []
        self._changes: dict[str, Any] = {}

    @property
    def version(self) -> int:
        """Current version of the aggregate."""
        return self._version

    @property
    def uncommitted_events(self) -> list[DomainEvent]:
        """Events generated but not yet persisted."""
        return self._uncommitted_events.copy()

    def apply_event(self, event: DomainEvent) -> None:
        """
        Apply an event to the aggregate state.
        This is called both during construction (from events) and when handling commands.
        """
        event_handler_name = self._get_event_handler_name(event.event_type)
        if hasattr(self, event_handler_name):
            handler = getattr(self, event_handler_name)
            handler(event)
        self._version = event.version

    def record_event(self, event: DomainEvent) -> None:
        """Record a new event (generated by this aggregate)."""
        self.apply_event(event)
        self._uncommitted_events.append(event)

    def mark_saved(self) -> None:
        """Clear uncommitted events after successful persistence."""
        self._uncommitted_events.clear()

    def _get_event_handler_name(self, event_type: str) -> str:
        """Convert event type to handler method name."""
        return f"_on_{event_type.lower()}"

    @classmethod
    def from_events(cls, aggregate_id: UUID, events: list[DomainEvent]) -> "BaseAggregate":
        """Reconstruct an aggregate from its event history."""
        aggregate = cls(aggregate_id)
        for event in events:
            aggregate.apply_event(event)
        aggregate.mark_saved()
        return aggregate

    def get_changes(self) -> dict[str, Any]:
        """Get pending changes."""
        return self._changes.copy()

    def clear_changes(self) -> None:
        """Clear pending changes."""
        self._changes.clear()

    def __eq__(self, other):
        if not isinstance(other, BaseAggregate):
            return False
        return self.id == other.id

    def __hash__(self):
        return hash(self.id)
