from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.models.imovel_model import ImovelModel
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.models.oneracao_model import OneracaoModel
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.models.proprietario_model import ProprietarioModel
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.models.desapropriacao_model import DesapropriacaoModel
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.models.matricula_imovel_model import MatriculaImovelModel
from app.modules.infrastructure_sector.gestao_fundiaria.infrastructure.models.georreferenciamento_model import GeorreferenciamentoModel
__all__ = ['ImovelModel', 'ProprietarioModel', 'OneracaoModel', 'DesapropriacaoModel', 'MatriculaImovelModel', 'GeorreferenciamentoModel']