from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_assinante_repository import SQLAlchemyAssinanteRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_espectro_repository import SQLAlchemyEspectroRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_fatura_repository import SQLAlchemyFaturaRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_indicador_qualidade_repository import SQLAlchemyIndicadorQualidadeRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_infraestrutura_repository import SQLAlchemyInfraestruturaRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_operadora_repository import SQLAlchemyOperadoraRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_outorga_espectro_repository import SQLAlchemyOutorgaEspectroRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_qualidade_servico_repository import SQLAlchemyQualidadeServicoRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_reclamacao_repository import SQLAlchemyReclamacaoRepository
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.repositories.sqlalchemy_sla_repository import SQLAlchemySLARepository
__all__ = ['SQLAlchemyOperadoraRepository', 'SQLAlchemyAssinanteRepository', 'SQLAlchemyInfraestruturaRepository', 'SQLAlchemyOutorgaEspectroRepository', 'SQLAlchemyEspectroRepository', 'SQLAlchemyFaturaRepository', 'SQLAlchemyReclamacaoRepository', 'SQLAlchemySLARepository', 'SQLAlchemyQualidadeServicoRepository', 'SQLAlchemyIndicadorQualidadeRepository']