"""Add IAM models tables

Revision ID: 2ccba150585d
Revises: 4a4962a762d2
Create Date: 2026-02-17 08:46:19.444895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccba150585d'
down_revision: Union[str, Sequence[str], None] = '4a4962a762d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iam_permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'resource', 'action', name='uq_permission_components')
    )
    op.create_index(op.f('ix_iam_permissions_action'), 'iam_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_iam_permissions_code'), 'iam_permissions', ['code'], unique=True)
    op.create_index(op.f('ix_iam_permissions_module'), 'iam_permissions', ['module'], unique=False)
    op.create_index('ix_iam_permissions_module_resource', 'iam_permissions', ['module', 'resource'], unique=False)
    op.create_index(op.f('ix_iam_permissions_resource'), 'iam_permissions', ['resource'], unique=False)
    op.create_index('ix_iam_permissions_resource_action', 'iam_permissions', ['resource', 'action'], unique=False)
    op.create_table('iam_roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iam_roles_name', 'iam_roles', ['name'], unique=False)
    op.create_index('ix_iam_roles_type', 'iam_roles', ['role_type'], unique=False)
    op.create_table('iam_users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_type', sa.String(length=50), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id', name='uq_iam_users_citizen_id')
    )
    op.create_index(op.f('ix_iam_users_citizen_id'), 'iam_users', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_iam_users_email'), 'iam_users', ['email'], unique=True)
    op.create_index('ix_iam_users_email_lower', 'iam_users', [sa.literal_column('lower(email)')], unique=False)
    op.create_index(op.f('ix_iam_users_status'), 'iam_users', ['status'], unique=False)
    op.create_index('ix_iam_users_status_created', 'iam_users', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_iam_users_username'), 'iam_users', ['username'], unique=True)
    op.create_index('ix_iam_users_username_lower', 'iam_users', [sa.literal_column('lower(username)')], unique=False)
    op.create_table('iam_audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iam_audit_logs_action'), 'iam_audit_logs', ['action'], unique=False)
    op.create_index('ix_iam_audit_logs_action_time', 'iam_audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_iam_audit_logs_resource'), 'iam_audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_iam_audit_logs_resource_id'), 'iam_audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_iam_audit_logs_resource_time', 'iam_audit_logs', ['resource', 'resource_id', 'created_at'], unique=False)
    op.create_index('ix_iam_audit_logs_search', 'iam_audit_logs', ['created_at', 'user_id', 'action'], unique=False)
    op.create_index(op.f('ix_iam_audit_logs_user_id'), 'iam_audit_logs', ['user_id'], unique=False)
    op.create_index('ix_iam_audit_logs_user_time', 'iam_audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('iam_refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iam_refresh_tokens_expires', 'iam_refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_iam_refresh_tokens_revoked', 'iam_refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_iam_refresh_tokens_token_hash'), 'iam_refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_iam_refresh_tokens_user', 'iam_refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_iam_refresh_tokens_user_id'), 'iam_refresh_tokens', ['user_id'], unique=False)
    op.create_table('iam_role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['iam_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['iam_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_iam_role_permissions_permission_id'), 'iam_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_iam_role_permissions_role_id'), 'iam_role_permissions', ['role_id'], unique=False)
    op.create_table('iam_token_blacklist',
    sa.Column('token_jti', sa.String(length=128), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by'], ['iam_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iam_token_blacklist_expires', 'iam_token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_iam_token_blacklist_token_jti'), 'iam_token_blacklist', ['token_jti'], unique=True)
    op.create_table('iam_user_permissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['iam_users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['iam_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission')
    )
    op.create_index('ix_iam_user_permissions_expires', 'iam_user_permissions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_iam_user_permissions_permission_id'), 'iam_user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_iam_user_permissions_user_id'), 'iam_user_permissions', ['user_id'], unique=False)
    op.create_table('iam_user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['iam_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['iam_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_iam_user_roles_role_id'), 'iam_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_iam_user_roles_user_id'), 'iam_user_roles', ['user_id'], unique=False)
    op.create_table('iam_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['iam_refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iam_sessions_expires', 'iam_sessions', ['expires_at'], unique=False)
    op.create_index('ix_iam_sessions_last_activity', 'iam_sessions', ['last_activity_at'], unique=False)
    op.create_index('ix_iam_sessions_user_active', 'iam_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_iam_sessions_user_id'), 'iam_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iam_sessions_user_id'), table_name='iam_sessions')
    op.drop_index('ix_iam_sessions_user_active', table_name='iam_sessions')
    op.drop_index('ix_iam_sessions_last_activity', table_name='iam_sessions')
    op.drop_index('ix_iam_sessions_expires', table_name='iam_sessions')
    op.drop_table('iam_sessions')
    op.drop_index(op.f('ix_iam_user_roles_user_id'), table_name='iam_user_roles')
    op.drop_index(op.f('ix_iam_user_roles_role_id'), table_name='iam_user_roles')
    op.drop_table('iam_user_roles')
    op.drop_index(op.f('ix_iam_user_permissions_user_id'), table_name='iam_user_permissions')
    op.drop_index(op.f('ix_iam_user_permissions_permission_id'), table_name='iam_user_permissions')
    op.drop_index('ix_iam_user_permissions_expires', table_name='iam_user_permissions')
    op.drop_table('iam_user_permissions')
    op.drop_index(op.f('ix_iam_token_blacklist_token_jti'), table_name='iam_token_blacklist')
    op.drop_index('ix_iam_token_blacklist_expires', table_name='iam_token_blacklist')
    op.drop_table('iam_token_blacklist')
    op.drop_index(op.f('ix_iam_role_permissions_role_id'), table_name='iam_role_permissions')
    op.drop_index(op.f('ix_iam_role_permissions_permission_id'), table_name='iam_role_permissions')
    op.drop_table('iam_role_permissions')
    op.drop_index(op.f('ix_iam_refresh_tokens_user_id'), table_name='iam_refresh_tokens')
    op.drop_index('ix_iam_refresh_tokens_user', table_name='iam_refresh_tokens')
    op.drop_index(op.f('ix_iam_refresh_tokens_token_hash'), table_name='iam_refresh_tokens')
    op.drop_index('ix_iam_refresh_tokens_revoked', table_name='iam_refresh_tokens')
    op.drop_index('ix_iam_refresh_tokens_expires', table_name='iam_refresh_tokens')
    op.drop_table('iam_refresh_tokens')
    op.drop_index('ix_iam_audit_logs_user_time', table_name='iam_audit_logs')
    op.drop_index(op.f('ix_iam_audit_logs_user_id'), table_name='iam_audit_logs')
    op.drop_index('ix_iam_audit_logs_search', table_name='iam_audit_logs')
    op.drop_index('ix_iam_audit_logs_resource_time', table_name='iam_audit_logs')
    op.drop_index(op.f('ix_iam_audit_logs_resource_id'), table_name='iam_audit_logs')
    op.drop_index(op.f('ix_iam_audit_logs_resource'), table_name='iam_audit_logs')
    op.drop_index('ix_iam_audit_logs_action_time', table_name='iam_audit_logs')
    op.drop_index(op.f('ix_iam_audit_logs_action'), table_name='iam_audit_logs')
    op.drop_table('iam_audit_logs')
    op.drop_index('ix_iam_users_username_lower', table_name='iam_users')
    op.drop_index(op.f('ix_iam_users_username'), table_name='iam_users')
    op.drop_index('ix_iam_users_status_created', table_name='iam_users')
    op.drop_index(op.f('ix_iam_users_status'), table_name='iam_users')
    op.drop_index('ix_iam_users_email_lower', table_name='iam_users')
    op.drop_index(op.f('ix_iam_users_email'), table_name='iam_users')
    op.drop_index(op.f('ix_iam_users_citizen_id'), table_name='iam_users')
    op.drop_table('iam_users')
    op.drop_index('ix_iam_roles_type', table_name='iam_roles')
    op.drop_index('ix_iam_roles_name', table_name='iam_roles')
    op.drop_table('iam_roles')
    op.drop_index('ix_iam_permissions_resource_action', table_name='iam_permissions')
    op.drop_index(op.f('ix_iam_permissions_resource'), table_name='iam_permissions')
    op.drop_index('ix_iam_permissions_module_resource', table_name='iam_permissions')
    op.drop_index(op.f('ix_iam_permissions_module'), table_name='iam_permissions')
    op.drop_index(op.f('ix_iam_permissions_code'), table_name='iam_permissions')
    op.drop_index(op.f('ix_iam_permissions_action'), table_name='iam_permissions')
    op.drop_table('iam_permissions')
    # ### end Alembic commands ###
