"""Add service requests tables

Revision ID: 30a2bcc8c697
Revises: 2ccba150585d
Create Date: 2026-02-17 12:40:12.736576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a2bcc8c697'
down_revision: Union[str, Sequence[str], None] = '2ccba150585d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_assignee_status', 'service_requests', ['assigned_to', 'status'], unique=False)
    op.create_index('ix_requests_citizen_status', 'service_requests', ['citizen_id', 'status'], unique=False)
    op.create_index('ix_requests_created_at', 'service_requests', ['created_at'], unique=False)
    op.create_index('ix_requests_deadline', 'service_requests', ['deadline'], unique=False)
    op.create_index('ix_requests_sla_due', 'service_requests', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_service_requests_assigned_to'), 'service_requests', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_service_requests_citizen_id'), 'service_requests', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_number'), 'service_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_service_requests_service_type'), 'service_requests', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_table('service_request_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_request', 'service_request_attachments', ['request_id'], unique=False)
    op.create_table('service_request_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_request', 'service_request_comments', ['request_id', 'created_at'], unique=False)
    op.create_table('service_request_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_actor', 'service_request_events', ['actor_id'], unique=False)
    op.create_index('ix_events_request', 'service_request_events', ['request_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_request', table_name='service_request_events')
    op.drop_index('ix_events_actor', table_name='service_request_events')
    op.drop_table('service_request_events')
    op.drop_index('ix_comments_request', table_name='service_request_comments')
    op.drop_table('service_request_comments')
    op.drop_index('ix_attachments_request', table_name='service_request_attachments')
    op.drop_table('service_request_attachments')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_service_type'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_number'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_citizen_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_assigned_to'), table_name='service_requests')
    op.drop_index('ix_requests_sla_due', table_name='service_requests')
    op.drop_index('ix_requests_deadline', table_name='service_requests')
    op.drop_index('ix_requests_created_at', table_name='service_requests')
    op.drop_index('ix_requests_citizen_status', table_name='service_requests')
    op.drop_index('ix_requests_assignee_status', table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
