"""add bi_records and identity_requests

Revision ID: 3aa2480df1a4
Revises: agt_002
Create Date: 2026-02-19 07:36:02.412640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa2480df1a4'
down_revision: Union[str, Sequence[str], None] = 'agt_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bi_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_fuc_id', sa.String(length=50), nullable=False),
    sa.Column('bi_number', sa.String(length=14), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reason_for_status', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_records_bi_number'), 'bi_records', ['bi_number'], unique=True)
    op.create_index(op.f('ix_bi_records_citizen_fuc_id'), 'bi_records', ['citizen_fuc_id'], unique=False)
    op.create_index(op.f('ix_bi_records_created_at'), 'bi_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_bi_records_status'), 'bi_records', ['status'], unique=False)
    op.create_table('identity_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_fuc_id', sa.String(length=50), nullable=False),
    sa.Column('service_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_requests_citizen_fuc_id'), 'identity_requests', ['citizen_fuc_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('service_code', sa.String(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_service_code'), 'permissions', ['service_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=True, comment='Liga ao cidadão no Ficheiro Único do Cidadão'),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen_fuc.citizen_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_citizen_id'), 'users', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_territory_id'), 'users', ['territory_id'], unique=False)
    op.drop_index(op.f('ix_comments_request'), table_name='service_request_comments')
    op.drop_table('service_request_comments')
    op.drop_table('statistics_aggregations')
    op.drop_index(op.f('ix_bi_dashboards_owner'), table_name='bi_dashboards')
    op.drop_table('bi_dashboards')
    op.drop_table('bi_reports')
    op.drop_index(op.f('ix_taxpayers_nif'), table_name='taxpayers')
    op.drop_table('taxpayers')
    op.drop_index(op.f('ix_bi_metrics_code'), table_name='bi_metrics')
    op.drop_index(op.f('ix_bi_metrics_period'), table_name='bi_metrics')
    op.drop_table('bi_metrics')
    op.drop_index(op.f('ix_statistics_code'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_timeseries_period_start'), table_name='statistics_timeseries')
    op.drop_index(op.f('ix_timeseries_statistic_id'), table_name='statistics_timeseries')
    op.drop_table('statistics_timeseries')
    op.alter_column('appointments', 'workflow_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('appointments', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('appointments', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_citizen_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_citizen_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_health_unit_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.alter_column('exam_requests', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_exam_requests_citizen_id'), table_name='exam_requests')
    op.drop_index(op.f('ix_exam_requests_doctor_id'), table_name='exam_requests')
    op.drop_index(op.f('ix_exam_requests_status'), table_name='exam_requests')
    op.alter_column('health_professionals', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('health_units', 'specialties',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('health_units', 'opening_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('health_units', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_health_units_municipality'), table_name='health_units')
    op.drop_index(op.f('ix_health_units_unit_type'), table_name='health_units')
    op.drop_index(op.f('ix_iam_roles_name'), table_name='iam_roles')
    op.create_index(op.f('ix_iam_roles_name'), 'iam_roles', ['name'], unique=True)
    op.alter_column('medical_records', 'allergies',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('medical_records', 'diagnosis_codes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('medical_records', 'prescription_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('medical_records', 'exam_request_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('medical_records', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_medical_records_citizen_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_health_unit_id'), table_name='medical_records')
    op.alter_column('prescriptions', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('prescriptions', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_prescriptions_citizen_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.add_column('service_request_attachments', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('service_request_attachments', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('service_request_attachments', sa.Column('storage_url', sa.String(length=2000), nullable=False))
    op.add_column('service_request_attachments', sa.Column('size_bytes', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_attachments_request'), table_name='service_request_attachments')
    op.create_index(op.f('ix_service_request_attachments_created_at'), 'service_request_attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_request_attachments_request_id'), 'service_request_attachments', ['request_id'], unique=False)
    op.drop_constraint(op.f('service_request_attachments_request_id_fkey'), 'service_request_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'service_request_attachments', 'service_requests', ['request_id'], ['id'])
    op.drop_column('service_request_attachments', 'file_name')
    op.drop_column('service_request_attachments', 'file_size')
    op.drop_column('service_request_attachments', 'file_path')
    op.drop_column('service_request_attachments', 'mime_type')
    op.drop_column('service_request_attachments', 'description')
    op.add_column('service_request_events', sa.Column('payload', sa.JSON(), nullable=True))
    op.alter_column('service_request_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_events_actor'), table_name='service_request_events')
    op.drop_index(op.f('ix_events_request'), table_name='service_request_events')
    op.create_index('ix_request_events_request_created', 'service_request_events', ['request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_service_request_events_created_at'), 'service_request_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_request_events_request_id'), 'service_request_events', ['request_id'], unique=False)
    op.drop_constraint(op.f('service_request_events_request_id_fkey'), 'service_request_events', type_='foreignkey')
    op.create_foreign_key(None, 'service_request_events', 'service_requests', ['request_id'], ['id'])
    op.drop_column('service_request_events', 'old_value')
    op.drop_column('service_request_events', 'event_metadata')
    op.drop_column('service_request_events', 'new_value')
    op.add_column('service_requests', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('service_requests', sa.Column('assigned_to_user_id', sa.UUID(), nullable=True))
    op.add_column('service_requests', sa.Column('workflow_instance_id', sa.UUID(), nullable=True))
    op.add_column('service_requests', sa.Column('workflow_data', sa.JSON(), nullable=True))
    op.add_column('service_requests', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('service_requests', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('service_requests', 'request_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('service_requests', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_requests_assignee_status'), table_name='service_requests')
    op.drop_index(op.f('ix_requests_citizen_status'), table_name='service_requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='service_requests')
    op.drop_index(op.f('ix_requests_deadline'), table_name='service_requests')
    op.drop_index(op.f('ix_requests_sla_due'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_assigned_to'), table_name='service_requests')
    op.create_index(op.f('ix_service_requests_assigned_to_user_id'), 'service_requests', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_service_requests_assignee_status', 'service_requests', ['assigned_to_user_id', 'status'], unique=False)
    op.create_index('ix_service_requests_citizen_status', 'service_requests', ['citizen_id', 'status'], unique=False)
    op.create_index('ix_service_requests_created_at', 'service_requests', ['created_at'], unique=False)
    op.create_index('ix_service_requests_deadline', 'service_requests', ['deadline'], unique=False)
    op.create_index('ix_service_requests_sla_due', 'service_requests', ['sla_due_at'], unique=False)
    op.create_index('ix_service_requests_submitted_at', 'service_requests', ['submitted_at'], unique=False)
    op.create_index('ix_service_requests_workflow', 'service_requests', ['workflow_instance_id'], unique=False)
    op.create_index(op.f('ix_service_requests_workflow_instance_id'), 'service_requests', ['workflow_instance_id'], unique=False)
    op.drop_column('service_requests', 'assigned_to')
    op.drop_column('service_requests', 'request_metadata')
    op.drop_column('service_requests', 'created_by')
    op.drop_column('service_requests', 'closed_at')
    op.alter_column('vaccine_doses', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_vaccine_doses_citizen_id'), table_name='vaccine_doses')
    op.drop_index(op.f('ix_vaccine_doses_vaccine_id'), table_name='vaccine_doses')
    op.alter_column('vaccines', 'contraindications',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('vaccines', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('wf_definitions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_wf_definitions_code'), table_name='wf_definitions')
    op.create_index(op.f('ix_wf_definitions_code'), 'wf_definitions', ['code'], unique=True)
    op.alter_column('wf_history', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_history', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_instances', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_instances', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_instances', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_wf_instances_assigned_to'), 'wf_instances', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_wf_instances_citizen_id'), 'wf_instances', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_wf_instances_entity_id'), 'wf_instances', ['entity_id'], unique=False)
    op.alter_column('wf_states', 'form_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_states', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_tasks', 'form_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_tasks', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_tasks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_wf_tasks_assigned_to'), 'wf_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_wf_tasks_status'), 'wf_tasks', ['status'], unique=False)
    op.alter_column('wf_transitions', 'pre_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_transitions', 'post_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('wf_transitions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wf_transitions', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_transitions', 'post_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_transitions', 'pre_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_wf_tasks_status'), table_name='wf_tasks')
    op.drop_index(op.f('ix_wf_tasks_assigned_to'), table_name='wf_tasks')
    op.alter_column('wf_tasks', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_tasks', 'result_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_tasks', 'form_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_states', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_states', 'form_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_wf_instances_entity_id'), table_name='wf_instances')
    op.drop_index(op.f('ix_wf_instances_citizen_id'), table_name='wf_instances')
    op.drop_index(op.f('ix_wf_instances_assigned_to'), table_name='wf_instances')
    op.alter_column('wf_instances', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_instances', 'context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_instances', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_history', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('wf_history', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_wf_definitions_code'), table_name='wf_definitions')
    op.create_index(op.f('ix_wf_definitions_code'), 'wf_definitions', ['code'], unique=False)
    op.alter_column('wf_definitions', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('vaccines', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vaccines', 'contraindications',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.create_index(op.f('ix_vaccine_doses_vaccine_id'), 'vaccine_doses', ['vaccine_id'], unique=False)
    op.create_index(op.f('ix_vaccine_doses_citizen_id'), 'vaccine_doses', ['citizen_id'], unique=False)
    op.alter_column('vaccine_doses', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('service_requests', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('service_requests', sa.Column('request_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_service_requests_workflow_instance_id'), table_name='service_requests')
    op.drop_index('ix_service_requests_workflow', table_name='service_requests')
    op.drop_index('ix_service_requests_submitted_at', table_name='service_requests')
    op.drop_index('ix_service_requests_sla_due', table_name='service_requests')
    op.drop_index('ix_service_requests_deadline', table_name='service_requests')
    op.drop_index('ix_service_requests_created_at', table_name='service_requests')
    op.drop_index('ix_service_requests_citizen_status', table_name='service_requests')
    op.drop_index('ix_service_requests_assignee_status', table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_assigned_to_user_id'), table_name='service_requests')
    op.create_index(op.f('ix_service_requests_assigned_to'), 'service_requests', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_requests_sla_due'), 'service_requests', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_requests_deadline'), 'service_requests', ['deadline'], unique=False)
    op.create_index(op.f('ix_requests_created_at'), 'service_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_citizen_status'), 'service_requests', ['citizen_id', 'status'], unique=False)
    op.create_index(op.f('ix_requests_assignee_status'), 'service_requests', ['assigned_to', 'status'], unique=False)
    op.alter_column('service_requests', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('service_requests', 'request_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('service_requests', 'completed_at')
    op.drop_column('service_requests', 'metadata')
    op.drop_column('service_requests', 'workflow_data')
    op.drop_column('service_requests', 'workflow_instance_id')
    op.drop_column('service_requests', 'assigned_to_user_id')
    op.drop_column('service_requests', 'created_by_user_id')
    op.add_column('service_request_events', sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_request_events', sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('service_request_events', sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'service_request_events', type_='foreignkey')
    op.create_foreign_key(op.f('service_request_events_request_id_fkey'), 'service_request_events', 'service_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_request_events_request_id'), table_name='service_request_events')
    op.drop_index(op.f('ix_service_request_events_created_at'), table_name='service_request_events')
    op.drop_index('ix_request_events_request_created', table_name='service_request_events')
    op.create_index(op.f('ix_events_request'), 'service_request_events', ['request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_actor'), 'service_request_events', ['actor_id'], unique=False)
    op.alter_column('service_request_events', 'event_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('service_request_events', 'payload')
    op.add_column('service_request_attachments', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_request_attachments', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('service_request_attachments', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('service_request_attachments', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_request_attachments', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_request_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('service_request_attachments_request_id_fkey'), 'service_request_attachments', 'service_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_request_attachments_request_id'), table_name='service_request_attachments')
    op.drop_index(op.f('ix_service_request_attachments_created_at'), table_name='service_request_attachments')
    op.create_index(op.f('ix_attachments_request'), 'service_request_attachments', ['request_id'], unique=False)
    op.drop_column('service_request_attachments', 'size_bytes')
    op.drop_column('service_request_attachments', 'storage_url')
    op.drop_column('service_request_attachments', 'content_type')
    op.drop_column('service_request_attachments', 'filename')
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_citizen_id'), 'prescriptions', ['citizen_id'], unique=False)
    op.alter_column('prescriptions', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('prescriptions', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_medical_records_health_unit_id'), 'medical_records', ['health_unit_id'], unique=False)
    op.create_index(op.f('ix_medical_records_doctor_id'), 'medical_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_records_citizen_id'), 'medical_records', ['citizen_id'], unique=False)
    op.alter_column('medical_records', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('medical_records', 'exam_request_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('medical_records', 'prescription_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('medical_records', 'diagnosis_codes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('medical_records', 'allergies',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_index(op.f('ix_iam_roles_name'), table_name='iam_roles')
    op.create_index(op.f('ix_iam_roles_name'), 'iam_roles', ['name'], unique=False)
    op.create_index(op.f('ix_health_units_unit_type'), 'health_units', ['unit_type'], unique=False)
    op.create_index(op.f('ix_health_units_municipality'), 'health_units', ['municipality'], unique=False)
    op.alter_column('health_units', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('health_units', 'opening_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('health_units', 'specialties',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('health_professionals', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_exam_requests_status'), 'exam_requests', ['status'], unique=False)
    op.create_index(op.f('ix_exam_requests_doctor_id'), 'exam_requests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_exam_requests_citizen_id'), 'exam_requests', ['citizen_id'], unique=False)
    op.alter_column('exam_requests', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_health_unit_id'), 'appointments', ['health_unit_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_citizen_id'), 'appointments', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_appointments_citizen_date'), 'appointments', ['citizen_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.alter_column('appointments', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('appointments', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('appointments', 'workflow_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_table('statistics_timeseries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statistic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('statistics_timeseries_pkey'))
    )
    op.create_index(op.f('ix_timeseries_statistic_id'), 'statistics_timeseries', ['statistic_id'], unique=False)
    op.create_index(op.f('ix_timeseries_period_start'), 'statistics_timeseries', ['period_start'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_module', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('statistics_pkey'))
    )
    op.create_index(op.f('ix_statistics_code'), 'statistics', ['code'], unique=False)
    op.create_table('bi_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_metrics_pkey'))
    )
    op.create_index(op.f('ix_bi_metrics_period'), 'bi_metrics', ['period'], unique=False)
    op.create_index(op.f('ix_bi_metrics_code'), 'bi_metrics', ['code'], unique=False)
    op.create_table('taxpayers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('citizen_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nif', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('taxpayers_pkey'))
    )
    op.create_index(op.f('ix_taxpayers_nif'), 'taxpayers', ['nif'], unique=True)
    op.create_table('bi_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_reports_pkey'))
    )
    op.create_table('bi_dashboards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_dashboards_pkey'))
    )
    op.create_index(op.f('ix_bi_dashboards_owner'), 'bi_dashboards', ['owner_id'], unique=False)
    op.create_table('statistics_aggregations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statistic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('statistics_aggregations_pkey'))
    )
    op.create_table('service_request_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('service_request_comments_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('service_request_comments_pkey'))
    )
    op.create_index(op.f('ix_comments_request'), 'service_request_comments', ['request_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_users_territory_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_citizen_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permissions_service_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_identity_requests_citizen_fuc_id'), table_name='identity_requests')
    op.drop_table('identity_requests')
    op.drop_index(op.f('ix_bi_records_status'), table_name='bi_records')
    op.drop_index(op.f('ix_bi_records_created_at'), table_name='bi_records')
    op.drop_index(op.f('ix_bi_records_citizen_fuc_id'), table_name='bi_records')
    op.drop_index(op.f('ix_bi_records_bi_number'), table_name='bi_records')
    op.drop_table('bi_records')
    # ### end Alembic commands ###
