"""baseline_clean

Revision ID: 4a4962a762d2
Revises: 
Create Date: 2026-02-16 23:12:19.945090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4962a762d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('citizen_fuc',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('citizen_id')
    )
    op.create_table('territories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['territories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territories_code'), 'territories', ['code'], unique=True)
    op.create_index(op.f('ix_territories_name'), 'territories', ['name'], unique=False)
    op.create_table('saude_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Enum('CONSULTA_GERAL', 'CONSULTA_ESPECIALIZADA', 'SAUDE_MATERNO_INFANTIL', 'PLANEAMENTO_FAMILIAR', 'ASSISTENCIA_PRE_NATAL', 'ASSISTENCIA_POS_NATAL', 'ACONSELHAMENTO_NUTRICIONAL', 'APOIO_PSICOLOGICO', 'ACOMPANHAMENTO_CRONICOS', 'ALERTAS_SAUDE', 'EDUCACAO_ALIMENTAR', 'MONITORIZACAO_NUTRICIONAL', name='healthcareservicetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=True),
    sa.Column('preferred_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('health_unit_id', sa.String(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen_fuc.citizen_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saude_requests_citizen_id'), 'saude_requests', ['citizen_id'], unique=False)
    op.create_index('ix_saude_requests_citizen_status', 'saude_requests', ['citizen_id', 'status'], unique=False)
    op.create_index(op.f('ix_saude_requests_service_type'), 'saude_requests', ['service_type'], unique=False)
    op.create_index(op.f('ix_saude_requests_status'), 'saude_requests', ['status'], unique=False)
    op.create_table('saude_chronic_monitoring',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='chronicseverity'), nullable=False),
    sa.Column('medication_plan', sa.Text(), nullable=True),
    sa.Column('monitoring_frequency', sa.String(), nullable=True),
    sa.Column('last_measurements', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['saude_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('saude_health_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.String(), nullable=True),
    sa.Column('notification_channel', sa.Enum('SMS', 'EMAIL', 'APP', name='notificationchannel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['saude_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('saude_maternal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('gestational_weeks', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='maternalrisklevel'), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('parity', sa.Integer(), nullable=True),
    sa.Column('prenatal_visits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['saude_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('saude_nutrition_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('nutritional_status', sa.String(), nullable=True),
    sa.Column('risk_category', sa.String(), nullable=True),
    sa.Column('diet_plan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['saude_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('saude_post_natal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('days_post_partum', sa.Integer(), nullable=False),
    sa.Column('healing_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['saude_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('saude_psychology_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('referral_needed', sa.Boolean(), nullable=True),
    sa.Column('suicide_risk_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['saude_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saude_psychology_sessions')
    op.drop_table('saude_post_natal_records')
    op.drop_table('saude_nutrition_records')
    op.drop_table('saude_maternal_records')
    op.drop_table('saude_health_alerts')
    op.drop_table('saude_chronic_monitoring')
    op.drop_index(op.f('ix_saude_requests_status'), table_name='saude_requests')
    op.drop_index(op.f('ix_saude_requests_service_type'), table_name='saude_requests')
    op.drop_index('ix_saude_requests_citizen_status', table_name='saude_requests')
    op.drop_index(op.f('ix_saude_requests_citizen_id'), table_name='saude_requests')
    op.drop_table('saude_requests')
    op.drop_index(op.f('ix_territories_name'), table_name='territories')
    op.drop_index(op.f('ix_territories_code'), table_name='territories')
    op.drop_table('territories')
    op.drop_table('citizen_fuc')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
