"""confirma tabelas identity_requests e bi_records

Revision ID: 9e59bb080964
Revises: 3aa2480df1a4
Create Date: 2026-02-19 08:02:33.813826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e59bb080964'
down_revision: Union[str, Sequence[str], None] = '3aa2480df1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iam_roles_name'), table_name='iam_roles')
    op.create_index('ix_iam_roles_name', 'iam_roles', ['name'], unique=False)
    op.alter_column('service_requests', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_requests', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_iam_roles_name', table_name='iam_roles')
    op.create_index(op.f('ix_iam_roles_name'), 'iam_roles', ['name'], unique=True)
    # ### end Alembic commands ###
