"""Clean, intentional no-op migration for agt_002.

Revision ID: agt_002
Revises: merge_agt_001
Create Date: 2026-02-19 00:21:14.914066

This migration intentionally performs no schema changes. The full
autogenerated output was backed up to
`alembic_core/backups/agt_002_agt_autogen_taxpayers_backup.py` for
review. We keep this no-op to preserve a clean, reviewable migration
history and avoid applying unrelated schema diff noise.
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'agt_002'
down_revision = 'merge_agt_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Intentionally empty — no automatic schema changes applied.
    return


def downgrade() -> None:
    return
