"""initial_autogen

Revision ID: c99ae146736f
Revises: 9e59bb080964
Create Date: 2026-02-19 09:09:10.768591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99ae146736f'
down_revision: Union[str, Sequence[str], None] = '9e59bb080964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_fuc', sa.Column('document_number', sa.String(length=32), nullable=True))
    op.add_column('citizen_fuc', sa.Column('vital_status', sa.String(length=32), nullable=True))
    op.add_column('citizen_fuc', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('citizen_fuc', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('citizen_fuc', sa.Column('fuc_sync_timestamp', sa.Date(), nullable=True))
    op.create_index(op.f('ix_citizen_fuc_document_number'), 'citizen_fuc', ['document_number'], unique=True)
    op.drop_index(op.f('ix_iam_roles_name'), table_name='iam_roles')
    op.create_index(op.f('ix_iam_roles_name'), 'iam_roles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iam_roles_name'), table_name='iam_roles')
    op.create_index(op.f('ix_iam_roles_name'), 'iam_roles', ['name'], unique=False)
    op.drop_index(op.f('ix_citizen_fuc_document_number'), table_name='citizen_fuc')
    op.drop_column('citizen_fuc', 'fuc_sync_timestamp')
    op.drop_column('citizen_fuc', 'phone')
    op.drop_column('citizen_fuc', 'email')
    op.drop_column('citizen_fuc', 'vital_status')
    op.drop_column('citizen_fuc', 'document_number')
    # ### end Alembic commands ###
