"""initial migration
Revision ID: 74535044d6a9
Revises:
Create Date: 2025-10-11 05:49:41.179363+00:00
"""

from __future__ import annotations
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "74535044d6a9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name: str = "") -> None:
    """Upgrade database schema and/or data, creating a new revision.
    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    with op.get_context().begin_transaction():
        # ### commands auto generated by Alembic - por favor, ajuste se necessário! ###
        op.create_table(
            "citizens",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("full_name", sa.String(length=255), nullable=False),
            sa.Column("document_id", sa.String(length=20), nullable=False),
            sa.Column("birth_date", sa.Date(), nullable=False),
            sa.Column("address", sa.String(length=255), nullable=False),
            sa.Column("district", sa.String(length=100), nullable=False),
            sa.Column("postal_code", sa.String(length=20), nullable=False),
            sa.Column("phone", sa.String(length=20), nullable=True),
            sa.Column("email", sa.String(length=100), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_citizens_document_id"), "citizens", ["document_id"], unique=True
        )
        op.create_index(op.f("ix_citizens_id"), "citizens", ["id"], unique=False)

        op.create_table(
            "citizenship_atualizacao_b_i",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("nome", sa.String(length=200), nullable=False),
            sa.Column("nome_en", sa.String(length=200), nullable=False),
            sa.Column("descricao", sa.String(length=500), nullable=True),
            sa.Column("descricao_en", sa.String(length=500), nullable=True),
            sa.Column("ativo", sa.Boolean(), nullable=False),
            sa.Column("data_criacao", sa.DateTime(), nullable=False),
            sa.Column("dados_adicionais", sa.JSON(), nullable=True),
            sa.Column("municipe_id", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_citizenship_atualizacao_b_i_id"),
            "citizenship_atualizacao_b_i",
            ["id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_citizenship_atualizacao_b_i_municipe_id"),
            "citizenship_atualizacao_b_i",
            ["municipe_id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_citizenship_atualizacao_b_i_nome"),
            "citizenship_atualizacao_b_i",
            ["nome"],
            unique=False,
        )

        op.create_table(
            "citizenship_emissao_b_i",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("nome", sa.String(length=200), nullable=False),
            sa.Column("nome_en", sa.String(length=200), nullable=False),
            sa.Column("descricao", sa.String(length=500), nullable=True),
            sa.Column("descricao_en", sa.String(length=500), nullable=True),
            sa.Column("ativo", sa.Boolean(), nullable=True),
            sa.Column("data_criacao", sa.DateTime(), nullable=True),
            sa.Column("dados_adicionais", sa.JSON(), nullable=True),
            sa.Column("municipe_id", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=50), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_citizenship_emissao_b_i_id"),
            "citizenship_emissao_b_i",
            ["id"],
            unique=False,
        )

        op.create_table(
            "citizenship_emissao_passaporte",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("nome", sa.String(length=200), nullable=False),
            sa.Column("nome_en", sa.String(length=200), nullable=False),
            sa.Column("descricao", sa.String(length=500), nullable=True),
            sa.Column("descricao_en", sa.String(length=500), nullable=True),
            sa.Column("ativo", sa.Boolean(), nullable=True),
            sa.Column("data_criacao", sa.DateTime(), nullable=True),
            sa.Column("dados_adicionais", sa.JSON(), nullable=True),
            sa.Column("municipe_id", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=50), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_citizenship_emissao_passaporte_id"),
            "citizenship_emissao_passaporte",
            ["id"],
            unique=False,
        )

        op.create_table(
            "permissions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_permissions_name"), "permissions", ["name"], unique=True
        )

        op.create_table(
            "region",
            sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("type", sa.String(), nullable=False),
            sa.Column(
                "parent_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True
            ),
            sa.ForeignKeyConstraint(["parent_id"], ["region.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_region_name"), "region", ["name"], unique=False)

        op.create_table(
            "registry_tutela_menor",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("nome", sa.String(length=200), nullable=False),
            sa.Column("nome_en", sa.String(length=200), nullable=False),
            sa.Column("descricao", sa.String(length=500), nullable=True),
            sa.Column("descricao_en", sa.String(length=500), nullable=True),
            sa.Column("ativo", sa.Boolean(), nullable=True),
            sa.Column("data_criacao", sa.DateTime(), nullable=True),
            sa.Column("dados_adicionais", sa.JSON(), nullable=True),
            sa.Column("municipe_id", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=50), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_registry_tutela_menor_id"),
            "registry_tutela_menor",
            ["id"],
            unique=False,
        )

        op.create_table(
            "roles",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)

        # Sanitation tables
        sanitation_tables = [
            "agente_sanitario",
            "controle_vetores",
            "educacao_ambiental",
            "esgoto_sanitario",
            "limpeza_urbana",
            "monitoramento_ambiental",
            "tratamento_agua",
        ]
        for table in sanitation_tables:
            op.create_table(
                f"sanitation_{table}",
                sa.Column("id", sa.Integer(), nullable=False),
                sa.Column("nome", sa.String(length=200), nullable=False),
                sa.Column("nome_en", sa.String(length=200), nullable=False),
                sa.Column("descricao", sa.String(length=500), nullable=True),
                sa.Column("descricao_en", sa.String(length=500), nullable=True),
                sa.Column("ativo", sa.Boolean(), nullable=True),
                sa.Column("data_criacao", sa.DateTime(), nullable=True),
                sa.Column("dados_adicionais", sa.JSON(), nullable=True),
                sa.Column("municipe_id", sa.Integer(), nullable=False),
                sa.Column("status", sa.String(length=50), nullable=True),
                sa.PrimaryKeyConstraint("id"),
            )
            op.create_index(
                op.f(f"ix_sanitation_{table}_id"),
                f"sanitation_{table}",
                ["id"],
                unique=False,
            )

        # Social tables
        social_tables = [
            "assistencia_mulher",
            "auxilio_social",
            "bolsa_familia",
            "capacitacao_profissional",
            "habitacao_social",
            "inclusao_digital",
            "programa_idoso",
            "protecao_menor",
            "reabilitacao_social",
            "seguranca_alimentar",
        ]
        for table in social_tables:
            op.create_table(
                f"social_{table}",
                sa.Column("id", sa.Integer(), nullable=False),
                sa.Column("nome", sa.String(length=200), nullable=False),
                sa.Column("nome_en", sa.String(length=200), nullable=False),
                sa.Column("descricao", sa.String(length=500), nullable=True),
                sa.Column("descricao_en", sa.String(length=500), nullable=True),
                sa.Column("ativo", sa.Boolean(), nullable=True),
                sa.Column("data_criacao", sa.DateTime(), nullable=True),
                sa.Column("dados_adicionais", sa.JSON(), nullable=True),
                sa.Column("municipe_id", sa.Integer(), nullable=False),
                sa.Column("status", sa.String(length=50), nullable=True),
                sa.PrimaryKeyConstraint("id"),
            )
            op.create_index(
                op.f(f"ix_social_{table}_id"), f"social_{table}", ["id"], unique=False
            )

        # Statistics tables
        stats_tables = [
            "analise_dados",
            "dashboard_executivo",
            "metricas_uso",
            "relatorio_k_p_i",
        ]
        for table in stats_tables:
            op.create_table(
                f"statistics_{table}",
                sa.Column("id", sa.Integer(), nullable=False),
                sa.Column("nome", sa.String(length=200), nullable=False),
                sa.Column("nome_en", sa.String(length=200), nullable=False),
                sa.Column("descricao", sa.String(length=500), nullable=True),
                sa.Column("descricao_en", sa.String(length=500), nullable=True),
                sa.Column("ativo", sa.Boolean(), nullable=True),
                sa.Column("data_criacao", sa.DateTime(), nullable=True),
                sa.Column("dados_adicionais", sa.JSON(), nullable=True),
                sa.Column("municipe_id", sa.Integer(), nullable=True),
                sa.Column("status", sa.String(length=50), nullable=True),
                sa.PrimaryKeyConstraint("id"),
            )
            op.create_index(
                op.f(f"ix_statistics_{table}_id"),
                f"statistics_{table}",
                ["id"],
                unique=False,
            )

        # Urbanism tables
        urbanism_tables = [
            "alvara_funcionamento",
            "demolicao_edificio",
            "espaco_publico",
            "inspecao_obra",
            "licenca_construcao",
            "loteamento_urbano",
            "ocupacao_solo",
            "plano_urbano",
            "regularizacao_fundiaria",
            "sinalizacao_trafego",
        ]
        for table in urbanism_tables:
            op.create_table(
                f"urbanism_{table}",
                sa.Column("id", sa.Integer(), nullable=False),
                sa.Column("nome", sa.String(length=200), nullable=False),
                sa.Column("nome_en", sa.String(length=200), nullable=False),
                sa.Column("descricao", sa.String(length=500), nullable=True),
                sa.Column("descricao_en", sa.String(length=500), nullable=True),
                sa.Column("ativo", sa.Boolean(), nullable=True),
                sa.Column("data_criacao", sa.DateTime(), nullable=True),
                sa.Column("dados_adicionais", sa.JSON(), nullable=True),
                sa.Column("municipe_id", sa.Integer(), nullable=False),
                sa.Column("status", sa.String(length=50), nullable=True),
                sa.PrimaryKeyConstraint("id"),
            )
            op.create_index(
                op.f(f"ix_urbanism_{table}_id"),
                f"urbanism_{table}",
                ["id"],
                unique=False,
            )

        op.create_table(
            "role_permissions",
            sa.Column("role_id", sa.Integer(), nullable=True),
            sa.Column("permission_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"]),
            sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
        )

        op.create_table(
            "users",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("email", sa.String(), nullable=False),
            sa.Column("hashed_password", sa.String(), nullable=False),
            sa.Column("full_name", sa.String(), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.Column("is_superuser", sa.Boolean(), nullable=True),
            sa.Column("is_verified", sa.Boolean(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "level",
                sa.Enum("LOCAL", "PROVINCIAL", "CENTRAL", name="administrativelevel"),
                nullable=True,
            ),
            sa.Column("region_id", sa.UUID(), nullable=True),
            sa.ForeignKeyConstraint(["region_id"], ["region.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

        op.create_table(
            "refreshtokens",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("token", sa.String(), nullable=True),
            sa.Column("user_id", sa.UUID(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_refreshtokens_token"), "refreshtokens", ["token"], unique=True
        )

        op.create_table(
            "user_permissions",
            sa.Column("user_id", sa.UUID(), nullable=True),
            sa.Column("permission_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        )
        # ### end Alembic commands ###


def downgrade(engine_name: str = "") -> None:
    """Downgrade database schema and/or data back to the previous revision.
    Args:
        engine_name: Database engine name. If not provided, applies to all engines.
    """
    if engine_name and engine_name != "postgresql":
        return

    with op.get_context().begin_transaction():
        # ### commands auto generated by Alembic - por favor, ajuste se necessário! ###
        op.drop_table("user_permissions")
        op.drop_index(op.f("ix_refreshtokens_token"), table_name="refreshtokens")
        op.drop_table("refreshtokens")
        op.drop_index(op.f("ix_users_email"), table_name="users")
        op.drop_table("users")
        op.drop_table("role_permissions")

        # Drop urbanism tables
        urbanism_tables = [
            "sinalizacao_trafego",
            "regularizacao_fundiaria",
            "plano_urbano",
            "ocupacao_solo",
            "loteamento_urbano",
            "licenca_construcao",
            "inspecao_obra",
            "espaco_publico",
            "demolicao_edificio",
            "alvara_funcionamento",
        ]
        for table in urbanism_tables:
            op.drop_index(
                op.f(f"ix_urbanism_{table}_id"), table_name=f"urbanism_{table}"
            )
            op.drop_table(f"urbanism_{table}")

        # Drop statistics tables
        stats_tables = [
            "relatorio_k_p_i",
            "metricas_uso",
            "dashboard_executivo",
            "analise_dados",
        ]
        for table in stats_tables:
            op.drop_index(
                op.f(f"ix_statistics_{table}_id"), table_name=f"statistics_{table}"
            )
            op.drop_table(f"statistics_{table}")

        # Drop social tables
        social_tables = [
            "seguranca_alimentar",
            "reabilitacao_social",
            "protecao_menor",
            "programa_idoso",
            "inclusao_digital",
            "habitacao_social",
            "capacitacao_profissional",
            "bolsa_familia",
            "auxilio_social",
            "assistencia_mulher",
        ]
        for table in social_tables:
            op.drop_index(op.f(f"ix_social_{table}_id"), table_name=f"social_{table}")
            op.drop_table(f"social_{table}")

        # Drop sanitation tables
        sanitation_tables = [
            "tratamento_agua",
            "monitoramento_ambiental",
            "limpeza_urbana",
            "esgoto_sanitario",
            "educacao_ambiental",
            "controle_vetores",
            "agente_sanitario",
        ]
        for table in sanitation_tables:
            op.drop_index(
                op.f(f"ix_sanitation_{table}_id"), table_name=f"sanitation_{table}"
            )
            op.drop_table(f"sanitation_{table}")

        op.drop_index(op.f("ix_roles_name"), table_name="roles")
        op.drop_table("roles")
        op.drop_index(
            op.f("ix_registry_tutela_menor_id"), table_name="registry_tutela_menor"
        )
        op.drop_table("registry_tutela_menor")
        op.drop_index(op.f("ix_region_name"), table_name="region")
        op.drop_table("region")
        op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
        op.drop_table("permissions")
        op.drop_index(
            op.f("ix_citizenship_emissao_passaporte_id"),
            table_name="citizenship_emissao_passaporte",
        )
        op.drop_table("citizenship_emissao_passaporte")
        op.drop_index(
            op.f("ix_citizenship_emissao_b_i_id"), table_name="citizenship_emissao_b_i"
        )
        op.drop_table("citizenship_emissao_b_i")
        op.drop_index(
            op.f("ix_citizenship_atualizacao_b_i_nome"),
            table_name="citizenship_atualizacao_b_i",
        )
        op.drop_index(
            op.f("ix_citizenship_atualizacao_b_i_municipe_id"),
            table_name="citizenship_atualizacao_b_i",
        )
        op.drop_index(
            op.f("ix_citizenship_atualizacao_b_i_id"),
            table_name="citizenship_atualizacao_b_i",
        )
        op.drop_table("citizenship_atualizacao_b_i")
        op.drop_index(op.f("ix_citizens_id"), table_name="citizens")
        op.drop_index(op.f("ix_citizens_document_id"), table_name="citizens")
        op.drop_table("citizens")
        # ### end Alembic commands ###
