from __future__ import annotations
from apps.backend.app.modules.economy.trade.external.application.ports import DrawbackSubstituicaoRepositoryPort
from apps.backend.app.modules.economy.trade.external.domain.models import DrawbackSubstituicao
from apps.backend.app.modules.economy.trade.external.infrastructure.repositories.in_memory_habilitacao_repository_base import InMemoryHabilitacaoRepositoryBase

class InMemoryDrawbackSubstituicaoRepository(InMemoryHabilitacaoRepositoryBase[DrawbackSubstituicao], DrawbackSubstituicaoRepositoryPort):
    pass