from __future__ import annotations
from apps.backend.app.modules.economy.trade.external.application.ports import HabilitacaoExportadorRepositoryPort
from apps.backend.app.modules.economy.trade.external.domain.models import HabilitacaoExportador
from apps.backend.app.modules.economy.trade.external.infrastructure.repositories.in_memory_habilitacao_repository_base import InMemoryHabilitacaoRepositoryBase

class InMemoryHabilitacaoExportadorRepository(InMemoryHabilitacaoRepositoryBase[HabilitacaoExportador], HabilitacaoExportadorRepositoryPort):
    pass