from app.modules.infrastructure_sector.telecomunicacoes.application.ports.assinante_repository_port import AssinanteRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.citizen_service_port import CitizenServicePort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.espectro_repository_port import EspectroRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.fatura_repository_port import FaturaRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.indicador_qualidade_repository_port import IndicadorQualidadeRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.infraestrutura_repository_port import InfraestruturaRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.operadora_repository_port import OperadoraRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.outorga_espectro_repository_port import OutorgaEspectroRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.qualidade_servico_repository_port import QualidadeServicoRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.request_service_port import RequestServicePort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.reclamacao_repository_port import ReclamacaoRepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.sla_repository_port import SLARepositoryPort
from app.modules.infrastructure_sector.telecomunicacoes.application.ports.outbox_repository_port import OutboxRepositoryPort
__all__ = ['OperadoraRepositoryPort', 'AssinanteRepositoryPort', 'InfraestruturaRepositoryPort', 'OutorgaEspectroRepositoryPort', 'EspectroRepositoryPort', 'FaturaRepositoryPort', 'ReclamacaoRepositoryPort', 'SLARepositoryPort', 'QualidadeServicoRepositoryPort', 'IndicadorQualidadeRepositoryPort', 'OutboxRepositoryPort', 'CitizenServicePort', 'RequestServicePort']