from apps.backend.app.modules.resources.florestas.api.endpoints.alertas_desmatamento import router as alertas_desmatamento_router
from apps.backend.app.modules.resources.florestas.api.endpoints.apreensoes_madeira import router as apreensoes_madeira_router
from apps.backend.app.modules.resources.florestas.api.endpoints.autorizacoes_supressao import router as autorizacoes_supressao_router
from apps.backend.app.modules.resources.florestas.api.endpoints.autos_infracao_florestais import router as autos_infracao_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.car_florestal import router as car_florestal_router
from apps.backend.app.modules.resources.florestas.api.endpoints.certificacoes_florestais import router as certificacoes_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.combates_incendio import router as combates_incendio_router
from apps.backend.app.modules.resources.florestas.api.endpoints.comercializacao_florestal import router as comercializacao_florestal_router
from apps.backend.app.modules.resources.florestas.api.endpoints.comunidades import router as comunidades_router
from apps.backend.app.modules.resources.florestas.api.endpoints.concessoes_florestais import router as concessoes_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.cras import router as cras_router
from apps.backend.app.modules.resources.florestas.api.endpoints.creditos_carbono import router as creditos_carbono_router
from apps.backend.app.modules.resources.florestas.api.endpoints.desmatamentos_ilegais import router as desmatamentos_ilegais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.dofs import router as dofs_router
from apps.backend.app.modules.resources.florestas.api.endpoints.embargos_florestais import router as embargos_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.empresas_florestais import router as empresas_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.especies_florestais import router as especies_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.estatisticas_florestais import router as estatisticas_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.exploracoes import router as exploracoes_router
from apps.backend.app.modules.resources.florestas.api.endpoints.exportacoes_madeira import router as exportacoes_madeira_router
from apps.backend.app.modules.resources.florestas.api.endpoints.fiscalizacoes_florestais import router as fiscalizacoes_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.focos_calor import router as focos_calor_router
from apps.backend.app.modules.resources.florestas.api.endpoints.incendios_florestais import router as incendios_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.inventarios import router as inventarios_router
from apps.backend.app.modules.resources.florestas.api.endpoints.licencas_manejo import router as licencas_manejo_router
from apps.backend.app.modules.resources.florestas.api.endpoints.madeiras import router as madeiras_router
from apps.backend.app.modules.resources.florestas.api.endpoints.monitoramentos_satelite import router as monitoramentos_satelite_router
from apps.backend.app.modules.resources.florestas.api.endpoints.multas_florestais import router as multas_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.ocorrencias_incendio import router as ocorrencias_incendio_router
from apps.backend.app.modules.resources.florestas.api.endpoints.operadores_florestais import router as operadores_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.outorgas_florestais import router as outorgas_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.planos_manejo import router as planos_manejo_router
from apps.backend.app.modules.resources.florestas.api.endpoints.pnfms import router as pnfms_router
from apps.backend.app.modules.resources.florestas.api.endpoints.produtos_florestais import router as produtos_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.projetos_carbono import router as projetos_carbono_router
from apps.backend.app.modules.resources.florestas.api.endpoints.recuperacoes_area import router as recuperacoes_area_router
from apps.backend.app.modules.resources.florestas.api.endpoints.redds import router as redds_router
from apps.backend.app.modules.resources.florestas.api.endpoints.reflorestamentos import router as reflorestamentos_router
from apps.backend.app.modules.resources.florestas.api.endpoints.reposicoes_florestais import router as reposicoes_florestais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.reservas_legais import router as reservas_legais_router
from apps.backend.app.modules.resources.florestas.api.endpoints.talhoes import router as talhoes_router
from apps.backend.app.modules.resources.florestas.api.endpoints.unidades_manejo import router as unidades_manejo_router
from apps.backend.app.modules.resources.florestas.api.endpoints.viveiros import router as viveiros_router
__all__ = ['alertas_desmatamento_router', 'apreensoes_madeira_router', 'autorizacoes_supressao_router', 'autos_infracao_florestais_router', 'car_florestal_router', 'certificacoes_florestais_router', 'combates_incendio_router', 'comercializacao_florestal_router', 'comunidades_router', 'concessoes_florestais_router', 'cras_router', 'creditos_carbono_router', 'desmatamentos_ilegais_router', 'dofs_router', 'embargos_florestais_router', 'empresas_florestais_router', 'especies_florestais_router', 'estatisticas_florestais_router', 'exploracoes_router', 'exportacoes_madeira_router', 'fiscalizacoes_florestais_router', 'focos_calor_router', 'incendios_florestais_router', 'inventarios_router', 'licencas_manejo_router', 'madeiras_router', 'monitoramentos_satelite_router', 'multas_florestais_router', 'ocorrencias_incendio_router', 'operadores_florestais_router', 'outorgas_florestais_router', 'planos_manejo_router', 'pnfms_router', 'produtos_florestais_router', 'projetos_carbono_router', 'recuperacoes_area_router', 'redds_router', 'reflorestamentos_router', 'reposicoes_florestais_router', 'reservas_legais_router', 'talhoes_router', 'unidades_manejo_router', 'viveiros_router']