name: Deploy Notifications

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Get workflow conclusion
        run: |
          echo "WORKFLOW_CONCLUSION=$(echo ${{ github.event.workflow_run.conclusion }})" >> $GITHUB_ENV

      - name: Notify on Slack
        if: env.WORKFLOW_CONCLUSION == 'success' || env.WORKFLOW_CONCLUSION == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on Discord
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: Ilshidur/action-discord@master
        with:
          args:
            "🚨 Deploy falhou! Verifique o workflow: https://github.com/${{
            github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
