from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.assinante_model import AssinanteModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.espectro_model import EspectroModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.fatura_model import FaturaTelecomModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.indicador_qualidade_model import IndicadorQualidadeModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.infraestrutura_telco_model import InfraestruturaTelcoModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.operadora_model import OperadoraModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.outorga_espectro_model import OutorgaEspectroModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.qualidade_servico_model import QualidadeServicoModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.reclamacao_model import ReclamacaoTelecomModel
from app.modules.infrastructure_sector.telecomunicacoes.infrastructure.models.sla_model import SLAModel
__all__ = ['OperadoraModel', 'AssinanteModel', 'InfraestruturaTelcoModel', 'OutorgaEspectroModel', 'EspectroModel', 'FaturaTelecomModel', 'ReclamacaoTelecomModel', 'SLAModel', 'QualidadeServicoModel', 'IndicadorQualidadeModel']